### ISSUE TITLE
Google_Service_Directory_Resource_Channels->stop() uses wrong URI

### ISSUE THREAD

**Issue by kiliansch** [googleapis/google-api-php-client-services#102]
When trying to call the mentioned endpoint, the URL being called is the following: `https://www.googleapis.com/admin/directory/v1//admin/directory_v1/channels/stop` instead of `https://www.googleapis.com/admin/directory_v1/channels/stop`.

**Comment by mattwhisenhunt** [comment]
Duplicate of #44

**Comment by dwsupplee** [comment]
Closing in favor of #44
