### ISSUE TITLE
Memory leak in Google_Service_Calendar_EventAttendee

### ISSUE THREAD

**Issue by vkulov** [googleapis/google-api-php-client-services#115]
We are experiencing out of memory conditions when listing events with large number of attendees. There seems to be some kind of memory leak related to Calendar Event Attendees.

**How to reproduce:**
Managed to reproduce it by creating a recurring event (daily) for a whole year and have 150 attendees in the event. When you list the events and the page size is set to 250 events per page (the default) we quickly run out of memory. 

PHP Memory jumps up to a 100MB

The error is reproducible every time.

**Error:**
Actual error we get is:
Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

**Workaround:**
Setting the page size to 100 seems to mitigate the issue.

**Environment**
We tested on php 7.1.15

**Comment by mattwhisenhunt** [comment]
Are the Google_Service_Calendar_EventAttendee objects big or do you suspect some leak in some C api: gzip, etc.

My initial instinct would be to use _fields_ to only get back the data for each attendee that you need: https://developers.google.com/drive/api/v3/performance#partial-response but I would need to know more details to be sure.

When you set the page size to 100 does it still does it still allocate 65-70 MB?

**Comment by vkulov** [comment]
I suspect some kind of circular reference in the EventAttendee class. Each event instance with 150 attendees takes about 60kb of memory and when you list a recurring event with `'singleEvents' => true` it adds up.

**Comment by dwsupplee** [comment]
It looks as though there is not a great way to address this without some type of breaking change, as it appears this is due to the nature of how the generated classes work. Since there is a good workaround here, by limiting the page size and/or by bumping up the memory limit assigned to PHP - I'm going to go ahead and close this out.

If you are consistently running in to this issue, please do reach out and let us know and we can work together to make plans to accommodate you.

**Comment by vkulov** [comment]
Limiting the page size is not a workaround as the pages are not getting released due to the circular reference and even a small page size is eating up your memory if you have large amount of pages.

We worked around this by calling
`$event->setAttendees(null);`
after we are done working with that particular event.

**Comment by dinamic** [comment]
@dwsupplee is there an update to this one? It's been two years, was the problem solved?
