### ISSUE TITLE
inAppProductRegionsMissingPricing when creating Google In-App products

### ISSUE THREAD

**Issue by Alqio** [googleapis/google-api-php-client-services#125]
This is the code that I use when creating new in app products:

```
$googlePrice = new \Google_Service_AndroidPublisher_Price();
$googlePrice->setCurrency($currency);
$googlePrice->setPriceMicros($priceInMicros);

$googleInAppProduct = new \Google_Service_AndroidPublisher_InAppProduct();

$googleInAppProduct->setDefaultPrice($googlePrice);
$googleInAppProduct->setSku($sku);
$googleInAppProduct->setStatus('active');
$googleInAppProduct->setPurchaseType($purchaseType);
$googleInAppProduct->setDefaultLanguage($defaultLanguage);
$googleInAppProduct->setPackageName($packageName);
$googleInAppProduct->setListings($listings);


$service->inappproducts->insert(
    $packageName,
    $googleInAppProduct,
    ['autoConvertMissingPrices' => true]
);
```

However, if the game in Google Play is published in many countries, this doesn't work. I get this error:

```
{
 "error": {
  "errors": [
   {
    "domain": "androidpublisher",
    "reason": "inAppProductRegionsMissingPricing",
    "message": "Must provide a price for each region the app has been published in."
   }
  ],
  "code": 403,
  "message": "Must provide a price for each region the app has been published in."
 }
}
```

Shouldn't the autoConvertMissingPrices convert the prices automatically based on the default price? Is this the correct way to provide it as this doesn't seem to work?

**Comment by mattwhisenhunt** [comment]
Good question. Let's make sure your request it getting to the server correctly. Try testing this in [API Explorer](https://developers.google.com/apis-explorer/#search/inappproducts/m/androidpublisher/v3/androidpublisher.inappproducts.insert) or with [Charles or mitmproxy](https://github.com/google/google-api-php-client/#debugging-your-http-request-using-charles) to make sure the PHP client isn't dropping that parameter.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
