### ISSUE TITLE
alt=>media or alt=>csv fails on report generation, adsense.

### ISSUE THREAD

**Issue by Pionell** [googleapis/google-api-php-client-services#134]
Hello, I've currently have an issue with report generation failing if I specify the alt value in the parameters. I need to generate a csv file with no row limit.
I bypassed the issue with csv by parsing the json into csv manually, however I'm still running into the row limit issue.
The code I'm using:
```
$adsense = new Google_Service_Adsense($client);
$reports = $adsense->reports;  
$csv = $reports->generate('2018-09-09','2018-09-09',array("metric" => ["EARNINGS"],"dimension"=>["DATE", "COUNTRY_CODE","APP_NAME"],"currency"=>"EUR","alt"=>"csv"));
```
OR 
```
$csv = $reports->generate('2018-09-09','2018-09-09',array("metric" => ["EARNINGS"],"dimension"=>["DATE", "COUNTRY_CODE","APP_NAME"],"currency"=>"EUR","alt"=>['media','csv']));
```

returns a "blank" result:
`Google_Service_AdSense_AdsenseReportsGenerateResponse Object ( [collection_key:protected] => warnings [averages] => [endDate] => [headersType:protected] => Google_Service_AdSense_AdsenseReportsGenerateResponseHeaders [headersDataType:protected] => array [kind] => [rows] => [startDate] => [totalMatchedRows] => [totals] => [warnings] => [internal_gapi_mappings:protected] => Array ( ) [modelData:protected] => Array ( ) [processed:protected] => Array ( ) )`
If I don't pass the alt array/parameter - the result is all fine and dandy.
Am I doing something wrong or is there an issue with the report generation?

**Comment by mattwhisenhunt** [comment]
When you specify an alt value `generate` will return a response object to get to the csv string call the 'getBody' method.

```php
$csv = $reports->generate('2018-09-09','2018-09-09', array(
    "metric" => ["EARNINGS"],
    "dimension"=>["DATE","COUNTRY_CODE","APP_NAME"],
    "currency"=>"EUR","alt"=>['media','csv']))
    ->getBody();
```

**Comment by mattwhisenhunt** [comment]
Thanks for filing this issue. Please add a comment if you have any other questions.

**Comment by Pionell** [comment]
Thanks, didn't notice the answer. Thank you!

**Comment by HelplessMan** [comment]
> Thanks for filing this issue. Please add a comment if you have any other questions.

hello,
I also encountered the same problem, try it according to your method, call the undefined method Google_Service_AdSense_AdsenseReportsGenerateResponse :: getBody()

code:
```
            $optParams = [
                'metric' => [
                    'REACHED_AD_REQUESTS',
                    'MATCHED_REACHED_AD_REQUESTS',
                    'EARNINGS',
                    'VIEWED_IMPRESSIONS',
                    'INDIVIDUAL_AD_IMPRESSIONS_CTR',
                    'INDIVIDUAL_AD_IMPRESSIONS_RPM',
                    'CLICKS',
                    'REACHED_AD_REQUESTS_SHOW_RATE'
                ],
                'dimension' => [
                    'APP_ID',
                    'APP_NAME',
                    'AD_UNIT_CODE',
                    'AD_UNIT_NAME',
                    'AD_CLIENT_ID',
                    'COUNTRY_CODE',
                    'DATE',
                    'AD_UNIT_SIZE_NAME'
                ],

                'sort' => '+DATE',
                'currency' => 'USD',
                'useTimezoneReporting' => true,
                'alt' => [
                    'media',
                    'csv'
                ],
                'filter' => [
                    //'APP_NAME==' . $app_name,
                    'APP_ID==' . $app,
                ]
            ];
            
            $response = $this->service->accounts_reports->generate($this->account_id,
                $start_date, $end_date, $optParams); // ->getBody()  call the undefined method
            dd($response);
            if (!isset($response) || empty($response['rows'])) {
                return [];
            }
```
