### ISSUE TITLE
error 500 Internal error encountered. from google local service ads

### ISSUE THREAD

**Issue by ardani** [googleapis/google-api-php-client-services#1340]
Hi,
I got error from google local service ads API.
Previously this service was working properly but yesterday this service returned error

```
{
 "error": {
 "code": 500,
 "message": "Internal error encountered.",
 "errors": [
 {
 "message": "Internal error encountered.",
 "domain": "global",
 "reason": "backendError"
 }
 ],
 "status": "INTERNAL"
 }
}
```

Here is my parameters
startDate.day => 02
startDate.month => 07
startDate.year => 2022
endDate.day => 31
endDate.month => 07
endDate.year => 2022
query => manager_customer_id:8034847770;customer_id:6452144301
pageSize => 10000

service https://github.com/googleapis/google-api-php-client-services/blob/main/src/Localservices.php

Is this issue with Google Local services ads? Or any missing from us?
Thanks

**Comment by vishwarajanand** [comment]
@ardani  could you please pass the code snippet you are using to call the API, along with the stack trace of this error?

Otherwise, I'll be shooting in the dark while debugging.

**Comment by vishwarajanand** [comment]
Closing this issue since there has been no update. Pls feel free to reopen.
