### ISSUE TITLE
Compute API missing classes

### ISSUE THREAD

**Issue by chingor13** [googleapis/google-api-php-client-services#138]
#51 incorrectly assumed that the HTTPSHealthCheck and HttpsHealthCheck files were identical when in fact they are 2 different classes ([first alpha discovery doc in the discovery-artifact-manager repo](https://raw.githubusercontent.com/googleapis/discovery-artifact-manager/893d18b7e3a7fe7155685e4e19eb41caa0699b22/discoveries/compute.alpha.json)).

We are seeing the duplicate file issue in the java generated code as well.

**Comment by mattwhisenhunt** [comment]
@chingor13 What is the state of apis-client-generator? Can we get PRs accepted to it now that it is in discovery-artifact-manager? If the Java fix has to go in there anyways can all the fixes to PHP services go in?

**Comment by chingor13** [comment]
Java doesn't have a fix and the compute API has been released with the double files for a long time. I don't believe we can just rename the files as that would be breaking the interface. For java, we do provide a Gapic generated client via google-cloud-java.

**Comment by tmatsuo** [comment]
@chingor13 Should we revert https://github.com/googleapis/google-api-php-client-services/pull/51 ? The PR is very old, so presumably no. Maybe we should remove those entries from `.gitignore` at least.

**Comment by chingor13** [comment]
We should not remove them from the .gitignore as it doesn't fix the problem either. Class names in PHP are case insensitive so if both files were to be loaded, then PHP would error. We probably need a way to alias one of the classes in the generator. It would technically be a breaking change, but that functionality never worked in the first place.

**Comment by chingor13** [comment]
@mattwhisenhunt Java is forking and moving its generator to the google-api-java-client-services repo so it can be modified and generated locally. We're still working on the automation for that repo but when it's finished, then we can do the same for the PHP generator and use a local generator from this repo.

**Comment by SurferJeffAtGoogle** [comment]
Is this issue still an issue?

**Comment by dwsupplee** [comment]
Yes, we've been discussing solutions.

**Comment by JustinBeckwith** [comment]
Fixing this at this stage would be a breaking change.  Given that no users appear to be running into, I'm going to close it out for now.

If folks stumble on this issue and want it fixed - please do let us know!  We'd be happy to re-open the issue.
