### ISSUE TITLE
People API: creating a new Person does not return resourceName

### ISSUE THREAD

**Issue by anonymous-explorer** [googleapis/google-api-php-client-services#140]
The following code creates a new person, but the $result does not contain resourceName, which I need to assign the person the contact group.
$client = new Google_Client();
...
$peopleService = new Google_Service_PeopleService($client);
...
 $person=new Google_Service_PeopleService_Person();
...
$result = $peopleService->people->createContact($person);

**Comment by anonymous-explorer** [comment]
unfortunately it does not work, resourceName is not returned.

> 
> 
> You can use fields to specify which you would like back in the response:
> 
> ```
> $opts = ['fields'=> 'resourceName,braggingRights,emailAddresses'];
> $result = $peopleService->people->createContact($person, $opts);
> ```

**Comment by mattwhisenhunt** [comment]
So after `$result = $peopleService->people->createContact($person, $opts);` successfully executes what is the value of `$result->resourceName`?

**Comment by anonymous-explorer** [comment]
my silly mistake was missing parenthesis at the end of $result->getResourceName();, so I always got null value
