### ISSUE TITLE
>feature reqest<  for the google play api

### ISSUE THREAD

**Issue by Pionell** [googleapis/google-api-php-client-services#141]
Hey, I noticed you guys are doing a great job.
Right now I have a solution for a problem, but it's a very ugly solution.
My problem: `I need to get installs of all my apps on a daily basis`. There is no wau to do this trough the api (unless I didn't found it yet), but it would make my life much much easier. What I have now is a shell script that gets launched by a cronjob. It downloads all the install metrics files (over 200 of them) into one of my folders using gsutil, then another cronojb launches a script that scans that directory for changed files and imports them into the dabatase. this takes a while and is nowhere near the solution it should be. Is there a way for the api to return json/csv data with install/retention data? What I need is metrics -> APP, INSTALLS, RETENTION_7_DAYS, OTHER_RETENTION_RATES, dimensions -> date.

**Comment by mattwhisenhunt** [comment]
Is this related to the issue you reported earlier this month #134 ? In any case, this isn't the place to request features for APIs, we're just a library to talk to the APIs. I don't think that feature request would be considered though, it seems to me you are looking for a categorically different set of statistics than what is offered by the Play API.

**Comment by Pionell** [comment]
Not related, need different statistics. Thanks though,

**Comment by mattwhisenhunt** [comment]
I don't have any first-hand experience with mobile development but my impression is that the metrics you are looking for are gathered by libraries built in at compile time. This is what I found on Google: https://support.google.com/analytics/answer/2587086?hl=en
