### ISSUE TITLE
Use array annotations in PHPDoc

### ISSUE THREAD

**Issue by holtkamp** [googleapis/google-api-php-client-services#148]
As related to adding PHPDoc https://github.com/googleapis/google-api-php-client-services/issues/88

It would be nice to have _proper_ PHPDoc support when dealing with collections:

https://github.com/googleapis/google-api-php-client-services/blob/50c4a818ad269839ad2c20f03828cd6f346ec887/src/Google/Service/Calendar/Events.php

Can be improved to (note the trailing `[]`):

```php
  /**
   * @param Google_Service_Calendar_Event[]
   */
  public function setItems($items)
  {
    $this->items = $items;
  }
```

**Comment by danielgsims** [comment]
Hi @holtkamp. Thanks for the feedback! We've had a few comments about PHPDoc support for arrays of objects. We'll definitely look into this in future iterations of our code generator which creates these libraries. Thanks!

**Comment by holtkamp** [comment]
Thanks for the response @danielgsims , but why close the issue then? 🤓 Better to keep it open until the issue has been resolved right? Or is there another issue covering the same subject?
