### ISSUE TITLE
INSERT request must not specify product.source

### ISSUE THREAD

**Issue by 719media** [googleapis/google-api-php-client-services#150]
When updating from 0.76 to 0.77 of this library, I get the following exceptions when issuing insert commands to products:

```
$googleShoppingService = new \Google_Service_ShoppingContent($credentials);
$someProduct = $googleShoppingService->products->get($merchantId, $productId);
//change some values for $someProduct
$googleShoppingService->products->insert($someProduct)
```

```
[Google_Service_Exception (400)]                                                  
  {                                                                                 
   "error": {                                                                       
    "errors": [                                                                     
     {                                                                              
      "domain": "global",                                                           
      "reason": "invalid",                                                          
      "message": "[product.source] INSERT request must not specify product.source"  
     }                                                                              
    ],                                                                              
    "code": 400,                                                                    
    "message": "[product.source] INSERT request must not specify product.source"    
   }                                                                                
  }
```

From what I can tell, the value of product->source is "api", which I am not setting, but appears to be a default value. In other words, I don't believe this error is something caused by my specific implementation.

I liked how before I could just send back the product to insert() with whatever changes and not having to check for values to unset.

**Comment by danielgsims** [comment]
I looked at the discovery documents for the Shopping Content API for both v2 and v2.1. The source property on product was never supported for the Insert operation. If it worked in previous versions, the API may have just ignored the fields. It looks like they reject that field now.

Unfortunately, you will need to explicitly set/unset the values on a product model that you want, until you are sending only the fields the operation expects.

I think that API team might be able to help you out if you let them know there was a backwards incompatibility introduced between v2 and 2.1: https://groups.google.com/forum/#!forum/google-content-api-for-shopping.

**Comment by 719media** [comment]
Thank you for the update. I've just used setSource(null)
