### ISSUE TITLE
Missing Google Shopping Content API Classes in v0.78

### ISSUE THREAD

**Issue by rvelhote** [googleapis/google-api-php-client-services#151]
Hello Google,

I recently updated from v0.73 to v0.78 (this was automatic via a composer update command) and a lot of the classes related to the Google Shopping Content API are gone.

- `Google_Service_ShoppingContent_InventoryCustomBatchRequest`
- `Google_Service_ShoppingContent_Inventory`

The underlying endpoint still works and I see no changes in the [documentation](https://developers.google.com/shopping-content/v2/reference/v2/inventory/custombatch).

Can someone please look into this? I am downgrading to the last known working version.

Thank you,
Ricardo Velhote

**Comment by carusogabriel** [comment]
A couple of other classes that are gone:
- `Google_Service_ShoppingContent_InventoryPickup`
- `Google_Service_ShoppingContent_ProductDestination`

**Comment by danielgsims** [comment]
Hi everyone! Recently, Version 2.1 of the Shopping Content API was released. The items you specified here were available in v2, but are missing from v2.1. Unfortunately, it looks like the documentation online is still targeting v2, but this library auto-generates code based on the latest published version.

If you need these options, you can use an earlier version of this API that still targets v2. 

If you would like to talk to the team behind the content API about this issue specifically, you find them here: https://groups.google.com/forum/#!forum/google-content-api-for-shopping. You can let them know the types you were looking for was in v2, but not v2.1.

Sorry for any inconvenience!

**Comment by timsweb** [comment]
@danielgsims whilst v2.1 has been released, it's still described as an "experimental version" in the docs and has breaking differences. 

Is this not the case? I'm somewhat reluctant to port my code over v2.1 until I know the api isn't going to change too much. I.e. no longer experimental.

**Comment by rvelhote** [comment]
Here is the reply by Lakshmi from the Content API Team to a [message](https://groups.google.com/forum/#!topic/google-content-api-for-shopping/DX4h2F7OGas) I left in the Google Content API Group:

> The v2.1 version is not completely available yet. As of now experimental version is released which doesn't include Inventory service. To conclude, the Inventory service under the v2.1 is considered but not available yet to the public.

@danielgsims Do you think it's possible to create stable and experimental branches for the google-api-php-client-services package? This way people can require the version they want in composer.
