### ISSUE TITLE
'includeInvalidInsertedItems' parameter is missing in v0.78

### ISSUE THREAD

**Issue by bubnysn** [googleapis/google-api-php-client-services#152]
google-api-php-client-services/src/Google/Service/ShoppingContent.php

 For 'Google_Service_ShoppingContent_Resource_Products' and 'Google_Service_ShoppingContent_Resource_Productstatuses' 
**'includeInvalidInsertedItems'** parameter is missing for 'list' operation in v0.78 but endpiont still works and such parameter still exists in Documentation. Please, check it and return back

**Comment by danielgsims** [comment]
Hi @bubnysn. I've looked into your issue. Recently, it looks as if the shopping content API has had version 2.1 released. Those options you listed were available in version 2. The current documentation still looks like it is based on v2 specifically.

If you need the options you specified, you can use an earlier version of this library that still leverages the v2 of the shopping content api.

If you would like to talk to the team behind the content API about this issue specifically, you find them here: https://groups.google.com/forum/#!forum/google-content-api-for-shopping. You can let them know the option you were looking for was in v2, but not v2.1.

Sorry for any inconvenience!
