### ISSUE TITLE
MyBusiness classes do not have scope constants like other classes

### ISSUE THREAD

**Issue by tobirehn** [googleapis/google-api-php-client-services#1535]
The Drupal module https://www.drupal.org/project/google_api_client uses the scope constants in the classes to populate the scope select field in the modules config UI. As the constants are missing in the class (and so the scopes) it is not possible to create an api client for MyBusiness-services.

The developer of the module pointed me to a similar issue https://github.com/googleapis/google-api-php-client-services/issues/382 where he has been told that those scope constants are autogenerated from the discovery docs. So it is not possible to create a pull request with the added constants.

https://mybusinessbusinessinformation.googleapis.com/$discovery/rest lacks the auth-property which is present in https://monitoring.googleapis.com/$discovery/rest for example and holds the oauth-scopes. As the Monitoring class has the scope constants it seems that adding the auth-property to the discovery doc might do the trick.

Could you please add the scopes in the MyBusiness* discovery docs? Maybe this is not the right place to file this issue. If it's not could you please point me in the right direction?

Many thanks in advance

**Comment by ConnectGrid** [comment]
I ran into this same issue. It seems to be because just a single scope is used by the entire MyBusiness API?

`https://www.googleapis.com/auth/business.manage`

Maybe I'm missing something, but that's the only one I've seen so far.

Agreed, it's inconsistent.

**Comment by yash30201** [comment]
Hi @tobirehn, sorry for such late reply.

Did @ConnectGrid's suggestion helped you on solving this? You can also look [here](https://developers.google.com/my-business/content/implement-oauth#authorization_scopes) and supply the respective scope and see if it works.

**Comment by vishwarajanand** [comment]
closing due to no response
