### ISSUE TITLE
Please adhere to the PSR-2

### ISSUE THREAD

**Issue by ribeirobreno** [googleapis/google-api-php-client-services#154]
This excerpt from [PHP-FIG](https://www.php-fig.org/) explains the reasoning:
> The intent of this guide is to reduce cognitive friction when scanning code from different authors. It does so by enumerating a shared set of rules and expectations about how to format PHP code.
>
>The style rules herein are derived from commonalities among the various member projects. When various authors collaborate across multiple projects, it helps to have one set of guidelines to be used among all those projects. Thus, the benefit of this guide is not in the rules themselves, but in the sharing of those rules.
>
> https://www.php-fig.org/psr/psr-2/

Since this is a code style change, is a pull request welcome?

**Comment by danielgsims** [comment]
Hi @ribeirobreno! Thanks for looking through our code and providing some feedback. This library is automatically generated, so any contributions will ultimately be overwritten! We will definitely take any standards recommendations from the PHP-FIG into consideration in future iterations.

**Comment by ribeirobreno** [comment]
Hi @danielgsims! Thanks for the feedback!
Can you point me in the direction of the generator repository then?
