### ISSUE TITLE
Explode this project is sub projects or provide a way to clean up unnecessary dependencies

### ISSUE THREAD

**Issue by dev-mansonthomas** [googleapis/google-api-php-client-services#155]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the Google App Engine Flex with PHP 7.2 (Beta).

When I'm uploading my project I got the following error  : 

```
Beginning deployment of service [default]...
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 16900 files to Google Cloud Storage            ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
ERROR: (gcloud.beta.app.deploy) INVALID_ARGUMENT: This deployment has too many files. New versions are limited to 10000 files for this app.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: This deployment has too many files. New versions are limited to 10000
      files for this app.
    field: version.deployment.files[...]
2019/01/19 14:39:23 Received TERM signal. Waiting up to 0s before terminating.
Updated property [core/project].
```

While if I look inside a previous version that runs PHP7.1, I can see that most of the files are from Google library, with a count of file already exceeding the limit : 11821 !

```
root@e7486400bc7d:/app/server/vendor# for i in $(ls -a); do echo -n "$i : "; find $i | wc -l; done 
. : 14922
.. : 15175
autoload.php : 1
bin : 3
composer : 10
container-interop : 21
firebase : 10
fzaninotto : 718
google : 11821
grpc : 20
guzzlehttp : 100
lcobucci : 99
monolog : 205
nesbot : 90
nikic : 50
paragonie : 14
phpmailer : 117
phpseclib : 43
pimple : 64
psr : 49
ralouphie : 11
ramsey : 65
rize : 35
robmorgan : 197
sendgrid : 198
slim : 72
symfony : 908
root@e7486400bc7d:/app/server/vendor#
```

And most of the files are from apiclient-services (and protobuf):

```
root@e7486400bc7d:/app/server/vendor/google# for i in $(ls -a); do echo -n "$i : "; find $i | wc -l; done 
. : 11821
.. : 14922
apiclient : 34
apiclient-services : 8801
auth : 93
cloud-core : 152
cloud-pubsub : 84
cloud-storage : 26
gax : 394
grpc-gcp : 29
protobuf : 2207
root@e7486400bc7d:/app/server/vendor/google# 
```

 **Describe the solution you'd like**

Have sub projects as dependencies to other project to be able to fetch only the dependencies that I need.

 **Describe alternatives you've considered**
A dirty workaround is described here : 

http://takaya030.hatenablog.com/entry/2017/07/17/181217

```
$ cd laravel
$ mv vendor/google/apiclient-services/src/Google/Service/Gmail /tmp
$ mv vendor/google/apiclient-services/src/Google/Service/Gmail.php /tmp
$ rm -rf vendor/google/apiclient-services/src/Google/Service/*
$ mv /tmp/Gmail vendor/google/apiclient-services/src/Google/Service/
$ mv /tmp/Gmail.php vendor/google/apiclient-services/src/Google/Service/

$ ls -FR | grep -v / | grep -v "^$" | wc -l
5832
```

**Comment by danielgsims** [comment]
Hey @dev-mansonthomas. Thanks for the detailed request!

Package splits is something that we've discussed for the future of this repo. We've tackled this with the Google Cloud PHP repos which is a newer library. Each of those packages are published as their own package, but are part of a bundled package as well. That being said, I don't have any timelines on any major changes to this library.

I'll keep this open as a feature request and hopefully we can have an answer to you in the near future!

**Comment by dev-mansonthomas** [comment]
Thanks for the feedback.

GCP AppEngine recently changed the number (to 10'000) of file that can be deployed, so now it's a blocker for deployment.

The mentioned workaround will help, but that's really dirty.

Maybe if a small script could help to identify, based on the composer.json, what are the files to be kept in this project for Deployment, an prepare a folder that we can then replace by the original, it would help a lot ;) and be quicker to implement than the project split.

There's some obvious stuff (if you have PubSub, you need PubSub.php and the folder), but it may be more complicated with some other libs. I've no idea.

**Comment by dev-mansonthomas** [comment]
In fact, It's not blocker, my project deployment was not good.

my project layout was : 
/                    # project root
gcp-deploy.sh # my deploy script
server/
server/composer.json # my dependencies
server/public_html # my project angular App
server/src/ # my project src
server/vendor/ # third party library (google-api-php-client-services included)

"gcloud app deploy -q"
was run from the project root
app.yaml had document_root : server/public_html
so when the docker image is being built, composer.json was not found at the root of the project (it's in server/composer.json)
So I had to keep the vender folder and the thousands of files.

Now, if run 
gcloud app deploy -q
from the server folder and change the document_root to public_html
the composer install  is done from the docker machine, so I don't have the issue with  the max number of file.

**Comment by danielgsims** [comment]
I'm glad you got it working. I'm going to close this issue, but we're definitely talking about how to best organize our libraries!
