### ISSUE TITLE
Latest release not listed on packagist.org

### ISSUE THREAD

**Issue by tfranke** [googleapis/google-api-php-client-services#159]
Hi,

it is currently impossible to install the latest release (v0.85) using composer as the repository on packagist.org lists v0.83 as the latest version.

https://packagist.org/packages/google/apiclient-services

`composer require google/apiclient-services v0.85`
returns
`  [InvalidArgumentException]
  Could not find package google/apiclient-services in a version matching v0.85`

**Comment by bizmate** [comment]
Strange `composer validate` does not return an error

**Comment by jdpedrie** [comment]
@bshaffer looks like we might need to update the Github webhook for this repository?

**Comment by dwsupplee** [comment]
This looks related to the following: https://twitter.com/packagist/status/1037035587453235201?lang=en

**Comment by bshaffer** [comment]
I updated the webhooks so this is now fixed. Version `0.85` is now available on packagist.
