### ISSUE TITLE
[Feature] Download Packages Selectively

### ISSUE THREAD

**Issue by erandagan** [googleapis/google-api-php-client-services#160]
**Is your feature request related to a problem? Please describe.**
App Engine Standard Environment has a[ limit of 10,000 files per version](https://cloud.google.com/appengine/quotas). The api services package contains almost 7500 files, which means it takes 75% of the max deployment size alone.

 **Describe the solution you'd like**
The api services packages of other languages, like NodeJS, are split into multiple packages (eg. `@google-cloud/service-name`). It would be great to have such option for PHP as well.

 **Describe alternatives you've considered**
For now I've resorted to a pretty dirty regex for the `skip_files` section in my service YAML description. It feels wrong and creates a big room for mistakes.

**Comment by jdpedrie** [comment]
You should not deploy the `vendor` folder. App Engine will run `composer install` on deployment. Be sure to leave the `vendor` folder in the `.gcloudignore` file for this reason. This will alleviate the file upload limits. Just make sure your `composer.lock` file is included in the deployment.

See [Specifying Dependencies](https://cloud.google.com/appengine/docs/standard/php7/specifying-dependencies) for more details.

That said, we are aware that separate packages would be useful for many people, and we are looking at potential options for the future.

**Comment by erandagan** [comment]
To the best of my knowledge, App Engine only supports the automatic Composer invocation on 2nd generation runtimes. The link you've mentioned also seems to support this, as all the 1st Gen runtimes are grayed out.

Unfortunately in my case the system has been running on the 1st Gen runtime for a few years now, so migrating is not an easy option ;)

**Comment by jdpedrie** [comment]
Ah, apologies for missing that. Yeah, it's on our radar, but unfortunately all I can suggest now is something similar to what you're doing.
