### ISSUE TITLE
Error when calling for new Google_Service_YouTubeAnalytics

### ISSUE THREAD

**Issue by saffabook** [googleapis/google-api-php-client-services#161]
Hi there, I am trying to migrate from youtube analytics V1 to V2 as per this documentation. 
[https://developers.google.com/youtube/analytics/migration](https://developers.google.com/youtube/analytics/migration)

After reading some more I came across this article below which pointed me to this Repo
[https://stackoverflow.com/questions/53024561/how-to-continue-accessing-youtube-analytics-api-with-php-client-library-googl](https://stackoverflow.com/questions/53024561/how-to-continue-accessing-youtube-analytics-api-with-php-client-library-googl)

I installed all the files in the service folder overriding the old. 
However when I try to get the analytics for youtube I get this error. 
**"status":"fail","code":"500","reason":"PHP error. Severity: Warning, Message: array_merge(): Argument #2 is not an array, File: Resource\/Reports.php, Line number: 90**

When I do a `new Google_Service_YouTube($client)` it works and I get my results with the new installation but with the  
`new Google_Service_YouTubeAnalytics($client)` I get the error above. 

So I assume everything is installed correctly as the first call works, any reason why youtubeAnalytics wont work?

Much appreciated.

**Comment by jdpedrie** [comment]
It sounds as though your call to `Google_Service_YouTubeAnalytics_Resource_Reports::query()` is incorrect. If you provide an argument, it must be a PHP array. The error you report shows that the argument is not of the proper type.

If you provide a code sample, I may be able to give more concrete guidance, but you might be able to resolve it yourself by verifying the method argument and correcting the type.

**Comment by saffabook** [comment]
Hi there thanks for you answer, much appreciated. 
I apologise for not being detailed enough, I hope this paints a better picture 

Ok a code sample 
I create the initial **$client** object ie 
```
$client = new Google_Client();
$client->setApplicationName('application name');
$client->setClientId($config['api_analytics_client_id']);
$client->setClientSecret($config['api_analytics_client_secret']);
$client->setAuthConfig($config['fileLocation']);
$client->setAccessToken($accessToken);
```
Then add the client object as below .... 
`$analytics = new Google_Service_YouTubeAnalytics($client);
`

I get return object and then...
```
$id = 'channel=='youtube_id;
$end_date = date('Y-m-d');
$start_date = date('Y-m-d', strtotime('-30 days'));
$optparams = array('dimensions' => 'day',);
$metric = 'views,estimatedMinutesWatched,averageViewDuration,comments,likes,dislikes,shares,subscribersGained,subscribersLost';
$api = $analytics->reports->query($id, $start_date, $end_date, $metric, $optparams);
```
This **$analytics->reports->query($id, $start_date, $end_date, $metric, $optparams);** is where the error is thrown. 
In the **google-api-php-client-services/src/Google/Service/YouTubeAnalytics/Resource/Reports.php** only a string comes through not an array. 

When looking at this file, there is this function
```
public function query($optParams = array())
  {
    $params = array();
    $params = array_merge($params, $optParams);
    return $this->call('query', array($params), "Google_Service_YouTubeAnalytics_QueryResponse");
  }
```
The error is that for **$optParams** an array does not come through but a string, something like **"channel==UCagdjkwlke-ksjd4v-ksjdfk"** 

So I guess the question is, am I doing the  **$analytics->reports->query($id, $start_date, $end_date, $metric, $optparams);** correctly or has this changed and there is some new way?
Why would a string come through there and not an array? 

This use to work with version one, but I cannot find good examples here 
[https://developers.google.com/youtube/reporting/v1/code_samples/php#create_a_reporting_job](https://developers.google.com/youtube/reporting/v1/code_samples/php#create_a_reporting_job)

Your time is appreciated.

**Comment by jdpedrie** [comment]
As you note in `Google_Service_YouTubeAnalytics_Resource_Reports`, `query()` accepts an array of parameters. That means that the arguments you are providing must be provided as members of `$optParams`, not as their own arguments.

```php
$response = $analytics->reports->query([
    'ids' => $id,
    'startDate' => $start_date,
    'endDate' => $end_date,
    'metrics' => $metric,
    'dimensions' => 'day'
]);
```

**Comment by saffabook** [comment]
ok, for some reason I was stuck on the old way. I have done as you suggested as that is logical :) thank you for that.  

However, the **google-api-php-client-services/src/Google/Service/YouTubeAnalytics/Resource/Reports.php** file, there is a line with this 
`return $this->call('query', array($params), "Google_Service_YouTubeAnalytics_QueryResponse");`

This does not return anything?

**Comment by jdpedrie** [comment]
Using the following code snippet, I received an instance of `Google_Service_YouTubeAnalytics_QueryResponse` as expected. Compare the code you're executing to what I've confirmed works as expected.

```php
$client = new Google_Client();
$client->setAuthConfig('/path/to/credentials.json');
$client->setAccessToken('[REDACTED]');
$client->addScope([
  Google_Service_YouTubeAnalytics::YOUTUBE
]);

$analytics = new Google_Service_YouTubeAnalytics($client);

$id = 'channel==[REDACTED]';
$end_date = date('Y-m-d');
$start_date = date('Y-m-d', strtotime('-30 days'));
$optparams = array('dimensions' => 'day',);
$metric = 'views,estimatedMinutesWatched,averageViewDuration,comments,likes,dislikes,shares,subscribersGained,subscribersLost';

$response = $analytics->reports->query([
  'ids' => $id,
  'startDate' => $start_date,
  'endDate' => $end_date,
  'metrics' => $metric,
  'dimensions' => 'day'
]);

print_r($response);
```

**Comment by saffabook** [comment]
After some further investigation, I had a look at the **$this->call()** function.
I am assuming that this [repo](https://github.com/googleapis/google-api-php-client) works with this one?

If so, I then am assuming that this will do the call for the **youtube analytics query**
Please look at **google-api-php-client/src/Google/Service/Resource.php** on line **136** there is 
`    foreach ($parameters as $key => $val) {
      if ($key != 'postBody' && ! isset($method['parameters'][$key])) {
        $this->client->getLogger()->error(
            'Service parameter unknown',
            array(
                'service' => $this->serviceName,
                'resource' => $this->resourceName,
                'method' => $name,
                'parameter' => $key
            )
        );
        throw new Google_Exception("($name) unknown parameter: '$key'");
      }
    }` 

I cannot get past this, why would that be?  

Please forgive my lack of understanding as its confusing as the migration code seems to point to me having to work with two separate repos.

**Comment by saffabook** [comment]
Thank you for your help, you have made my day :) 

Its all working as expected. Very much appreciate and a toast to your patience. 
Have a great day.

**Comment by jdpedrie** [comment]
Yes, that's right. This repo is intended to be used via the `google-api-php-client`.

I'm glad to hear that you were able to get it working!
