### ISSUE TITLE
Ads Data Hub service

### ISSUE THREAD

**Issue by tonycoco** [googleapis/google-api-php-client-services#167]
https://developers.google.com/ads-data-hub/reference/rest/

**Comment by dwsupplee** [comment]
@tonycoco unfortunately, if a service isn't listed in [the discovery API](https://discovery.googleapis.com/discovery/v1/apis) there won't be a client generated for it. The best route forward would likely be to reach out [to the service's support](https://developers.google.com/ads-data-hub/support) to see if they'll be able to get it added.
