### ISSUE TITLE
Ability to set Cluster Scheduled Deletion

### ISSUE THREAD

**Issue by cri699** [googleapis/google-api-php-client-services#171]
It will be good to have the support for [LifecycleConfig](https://cloud.google.com/dataproc/docs/reference/rest/v1beta2/ClusterConfig#LifecycleConfig) on Dataproc/ClusterConfig

**Comment by jdpedrie** [comment]
Hi @cri699,

[LifecycleConfig](https://github.com/googleapis/google-cloud-php/blob/master/Dataproc/src/V1beta2/LifecycleConfig.php) is available as part of the v1beta2 client on [`google/cloud-dataproc`](https://packagist.org/packages/google/cloud-dataproc).

Generally speaking, if an API client is available as part of [`google-cloud-php`](https://github.com/googleapis/google-cloud-php), it should be preferred over the client in Google API PHP Client.

If that doesn't work for you, please feel free to re-open this issue. :)
