### ISSUE TITLE
Improve PHPDoc to (generated?) models to increase usability

### ISSUE THREAD

**Issue by holtkamp** [googleapis/google-api-php-client-services#172]
As requested, this is a new issue for https://github.com/googleapis/google-api-php-client-services/issues/28#issuecomment-314583187

 **Is your feature request related to a problem? Please describe.**
The generated PHPDoc can be improved, for example this line: https://github.com/googleapis/google-api-php-client-services/blob/d41fea99f90d7935bd57cf654bf271072fe584f1/src/Google/Service/Calendar/Events.php#L81

The proper return type would probably suggest an array / collection, so `@return Google_Service_Calendar_Event[]` would be better: suggest it is iterable.

Currently my IDE (PHPStorm) still needs an explicit typehint:

```php
/* @var GoogleCalendarEvent $calendarEvent */
foreach ($calendarEvents->getItems() as $calendarEvent) {
    echo $calendarEvent->getStart()->getDateTime();
}
```

 **Describe the solution you'd like**
Indicate cardinality in PHPDoc return types

 **Describe alternatives you've considered**
Using typehints in userland code can used as workaround, but this is quite error-prone and not very "intelligent"...

**Comment by NicoHaase** [comment]
Same here, PHPStan complains that `\Google_Service_Calendar_Event::getAttendees` returns an array of attendees instead of a single instance of `Google_Service_Calendar_EventAttendee` as given in the docblock

**Comment by holtkamp** [comment]
@dwsupplee and @jdpedrie is this somewhere on a roadmap / your radar? Seems "low hanging fruit" to me (of course, no idea whether that is the case, might be way more complex than I think...)

**Comment by dwsupplee** [comment]
@holtkamp thanks for the ping. It is indeed! We've got a handful of changes we are working on batching up together in our code generator.

**Comment by dwsupplee** [comment]
I just wanted to raise awareness this is still on our radar, and thank everyone for their patience.

**Comment by Kocal** [comment]
Typings of `\Google_Service_Analytics_Webproperties::getItems` and `\Google_Service_Analytics_Webproperties::setItems` are incorrect too, they should use `Google_Service_Analytics_Webproperty[]`, not `Google_Service_Analytics_Webproperty`.

**Comment by holtkamp** [comment]
@dwsupplee thanks for https://github.com/googleapis/google-api-php-client-services/issues/172#issuecomment-575410314 and letting us know this is still on the radar

Just wanted to point out that the [original issue](https://github.com/googleapis/google-api-php-client-services/issues/28#issue-171125451) was submitted in August 2016...

Maybe it might be a nice challenge wrap up before / around August 2020? 😇

**Comment by holtkamp** [comment]
I suppose with https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.200.0 this issue has been resolved => close issue 🥳
