### ISSUE TITLE
Please add support for all options on RecognitionConfig

### ISSUE THREAD

**Issue by paulsheldrake** [googleapis/google-api-php-client-services#173]
When you are creating the RecognitionConfig object there are no methods to set the following properties which could improve our transcription results.

RecognitionMetadata
SpeakerDiarizationConfig
SpeechContext

This issue needs to be in this project https://github.com/googleapis/google-cloud-php-speech but you can't add issues there

**Comment by jdpedrie** [comment]
Moved to https://github.com/googleapis/google-cloud-php/issues/2112.
