### ISSUE TITLE
Drive permissions 

### ISSUE THREAD

**Issue by afagard** [googleapis/google-api-php-client-services#174]
Following the docs here:

https://developers.google.com/drive/api/v2/reference/permissions/insert

Yields the following error: Call to undefined method Google_Service_Drive_Permission::setValue()

It seems the entire permissions system was revised. How can one add a permission  now?

**Comment by jdpedrie** [comment]
Please refer to [Google Drive API v3 `permissions.create`](https://developers.google.com/drive/api/v3/reference/permissions/create).

```php
$documentId = '<Document ID>';

$drive = new Google_Service_Drive($client);
$permission = new Google_Service_Drive_Permission();
$permission->setRole('commenter');
$permission->setType('user');
$permission->setEmailAddress('<Email Address>');

$drive->permissions->create($documentId, $permission);
```

If you continue to have issues, please reopen and share your code and new errors.
