### ISSUE TITLE
Google Shopping Custom attribute type

### ISSUE THREAD

**Issue by maxbaldanza** [googleapis/google-api-php-client-services#177]
We are using the Shopping content API to send across product data via the Products API and we are sending across custom attributes.

We are getting a lot of these errors:
```{ "error": { "errors": [ { "domain": "global", "reason": "required", "message": "[customAttribute.type] Required parameter: customAttribute.type" }, { "domain": "content.ContentErrorDomain", "reason": "not_inserted", "message": "The item could not be inserted." } ], "code": 400, "message": "[customAttribute.type] Required parameter: customAttribute.type" } }```

According to the documentation we'd send across the custom attribute type: https://developers.google.com/shopping-content/v2/reference/v2/products/insert

`customAttributes[].type` - The type of the attribute.

Looking at the [Google_Service_ShoppingContent_CustomAttribute](https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/ShoppingContent/CustomAttribute.php) class I can't see how we can add this.
Is this supported?

**Comment by jdpedrie** [comment]
@maxbaldanza Can you provide a code sample demonstrating the issue?

**Comment by maxbaldanza** [comment]
Thanks for the quick reply @jdpedrie.

Here's some sample code that produces the error for us:
```<?php
include_once __DIR__ . '/../vendor/autoload.php';

$client = new Google_Client();
$client->setAuthConfig(__DIR__ .  '/../service-account.json');
$client->setScopes(Google_Service_ShoppingContent::CONTENT);
$client->useApplicationDefaultCredentials();
$client->setUseBatch(true);

$service = new Google_Service_ShoppingContent($client);
$batch = $service->createBatch();

$merchant_id = 'xxxxxxx';

$products = [];

$product = new Google_Service_ShoppingContent_Product();
$product->setOfferId('00002');
$product->setAvailability('in stock');
$product->setChannel('online');
$product->setContentLanguage('en');
$product->setTargetCountry('GB');
$product->setLink('http://127.0.0.1/test');
$product->setImageLink('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png');
$product->setTitle('Test');

$price = new Google_Service_ShoppingContent_Price();
$price->setValue('12.00');
$price->setCurrency('GBP');
$product->setPrice($price);

$customAttribute = new Google_Service_ShoppingContent_CustomAttribute();
$customAttribute->setName('weight');
$customAttribute->setValue('10');

$product->setCustomAttributes([$customAttribute]);

$products[] = $product;

$product = new Google_Service_ShoppingContent_Product();
$product->setOfferId('00091');
$product->setAvailability('in stock');
$product->setChannel('online');
$product->setContentLanguage('en');
$product->setTargetCountry('GB');
$product->setLink('http://127.0.0.1/test1');
$product->setImageLink('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png');
$product->setTitle('Test');

$price = new Google_Service_ShoppingContent_Price();
$price->setValue('12.00');
$price->setCurrency('GBP');
$product->setPrice($price);

$product->setCustomAttributes([]);

$products[] = $product;

foreach ($products as $product) {
    $req1 = $service->products->insert($merchant_id, $product);
    $batch->add($req1, $product->getOfferId());
}

$results = $batch->execute();
foreach ($results as $result) {
    var_dump($result);
}
```

**Comment by jdpedrie** [comment]
Sorry for the delayed response, @maxbaldanza.

It appears that this may be an issue in the API. As this client is generated, we're limited in what we can do to resolve certain issues here. I suggest you post this question on the [support forum](https://groups.google.com/forum/#!forum/google-content-api-for-shopping) and the API team will be in a better position to assist. Apologies that we're not able to get you a more immediate answer.
