### ISSUE TITLE
get account sub-account tree empty

### ISSUE THREAD

**Issue by HelplessMan** [googleapis/google-api-php-client-services#178]
hello,
I want to get the sub-account tree under my current account by account id, get it according to the examples method, and respond to an empty object. In fact, the account has been bound to 7 sub accounts.

[https://github.com/googleads/googleads-adsense-examples/blob/master/php-clientlib-1.x/v1.x/examples/GetAccountTree.php](examples)

```
        $pageToken = null;
        $optParams['maxResults'] = 500;
        $optParams['pageToken'] = $pageToken;
        $result = $this->service->accounts->listAccounts($optParams);
        $accounts = null;

        if (!empty($result['items'])) {
            $accounts = $result['items'];
            foreach ($accounts as $account) {
                $this->account_id = $account['id'];
            }
        }
        $subAccounts = $this->service->accounts->get($this->account_id, array('tree' => true));
        if (!empty($subAccounts['subAccounts'])){
            foreach ($subAccounts['subAccounts']  as $account) {
                dump($account);
            }
        }
    dd($subAccounts); 
```

response:
```
Google_Service_AdSense_Account^ {#1363
  #collection_key: "subAccounts"
  #internal_gapi_mappings: array:1 [
    "creationTime" => "creation_time"
  ]
  +creationTime: "1551266190244"
  +id: "pub-*********"
  +kind: "adsense#account"
  +name: "*********"
  +premium: false
  #subAccountsType: "Google_Service_AdSense_Account"
  #subAccountsDataType: "array"
  +timezone: "Europe/London"
  #modelData: array:1 [
    "creation_time" => "1551266190244"
  ]
  #processed: []
}
```

There is a weird problem if I dump ` dd($subAccounts,$subAccounts['subAccounts']);`

response:
```
Google_Service_AdSense_Account^ {#1363
  #collection_key: "subAccounts"
  #internal_gapi_mappings: array:1 [
    "creationTime" => "creation_time"
  ]
  +creationTime: "1551266190244"
  +id: "pub-*********"
  +kind: "adsense#account"
  +name: "*********"
  +premium: false
  #subAccountsType: "Google_Service_AdSense_Account"
  #subAccountsDataType: "array"
  +timezone: "Europe/London"
  #modelData: array:2 [
    "creation_time" => "1551266190244"
    "subAccounts" => []
  ]
  #processed: array:1 [
    "subAccounts" => true  //  not empty
  ]
}
```

**Comment by HelplessMan** [comment]
@yoshi-automation hello  Can you help me? this is important to me , Thank you

**Comment by jdpedrie** [comment]
Hi @HelplessMan,

Your code appears correct; you've toggled the `tree` option in the request. Given that it appears to be an API issue rather than a client issue, we're unfortunately not well situated to assist here. The Adsense team suggests using Stackoverflow with the [`adsense-api`](https://stackoverflow.com/questions/tagged/adsense-api) tag for product support. They monitor that tag and should be able to assist there. The report you provided here was good, I'd suggest sharing the same information in the Stackoverflow question, and be sure to specifically mention that you did set `tree` to `true`.

I'm sorry we're unable to answer the question here, if there were a quicker way to get you an answer I'd definitely offer it. Best of luck!

**Comment by HelplessMan** [comment]
@jdpedrie  
Thank you very much for your answer. I have already asked questions Stackoverflow  a week ago, but no one answered.

**Comment by jdpedrie** [comment]
Can you share the link to your stackoverflow question?

**Comment by HelplessMan** [comment]
Here, [`get account sub account tree empty`](https://stackoverflow.com/questions/57394170/get-account-sub-account-tree-empty) , I didn't know The Adsense team suggests using Stackoverflow with the [`adsense-api`](https://stackoverflow.com/questions/tagged/adsense-api) tag for product support at first, but the set tag is php and api, I have edited it but it didn't success. But now it has been changed to adsense api tag
