### ISSUE TITLE
Pagespeed Insights API does not return best-practices category in categories node

### ISSUE THREAD

**Issue by blue-eyed-devil** [googleapis/google-api-php-client-services#180]
#### Environment details

  - OS: Linux
  - PHP version: PHP 7.3.8
  - Package name and version:

#### Code example

```php
$url = 'https:// ...';
$options = [
	'strategy' => 'mobile',
	'category' => ['accessibility','best-practices','performance','pwa','seo'],
	'fields' => 'lighthouseResult/categories'
];
$pagespeedonlineService = new Google_Service_Pagespeedonline($google_OAuthclient);
$pagespeedApi = $pagespeedonlineService->pagespeedapi;
$results = $pagespeedApi->runpagespeed($url, $options);
```

**Comment by jdpedrie** [comment]
Hi @blue-eyed-devil,

Sorry to hear you're having trouble. Unfortunately, this forum is only able to assist with resolving questions related to the client library itself. While we are sometimes able to determine the answer to API-specific questions, after doing a bit of research, I don't think that this is one of those cases.

I suggest you pose this question on the [pagespeed-insights Google group](https://groups.google.com/forum/#!forum/pagespeed-insights-discuss) or [Stackoverflow](https://stackoverflow.com/questions/tagged/pagespeed-insights).

Best of luck!

**Comment by marinabrook** [comment]
i guess this is php client issues, the response not set
