### ISSUE TITLE
setLinkedPeopleResourceNames not working

### ISSUE THREAD

**Issue by morsanu** [googleapis/google-api-php-client-services#182]
#### Environment details

  - OS: Windows
  - PHP version: 7.2
  - Package name and version: Google API Client v2.2.3

#### Steps to reproduce

1.  Create a new person
2.  Create a new person metadata object
3.  Set Linked Resource Names property of the metadata, containing array with "people/id" resource names
4.  Attach metadata to person
5.  Create the person using People Service
6.  When retrieving the newly created person using the following person fields"names,metadata,nicknames,emailAddresses,phoneNumbers", the metadata object doesn't contain the Linked Resources

#### Code example

```php
# $metadata = new \Google_Service_PeopleService_PersonMetadata();
# $metadata->setLinkedPeopleResourceNames(array($linkedResourceID));
# $person->setMetadata($metadata);
```

**Comment by jdpedrie** [comment]
I've run some tests and encountered the same behavior. It seems that this is likely an issue in the upstream service. This forum can only really assist with problems in the API client. Take a look at the [How to get help](https://developers.google.com/people/support) document. Stackoverflow or the issue tracker may be a better place to get assistance with this one.

**Comment by morsanu** [comment]
Thank you for the answer, I'll try your suggestions.

**Comment by morsanu** [comment]
@jdpedrie By the way, do you know about any other way to mark a contact as a duplicate of another?

**Comment by jdpedrie** [comment]
@morsanu no, unfortunately. I'm not especially familiar with the people service API. My experience is limited to reading the API docs to answer questions similar to yours.
