### ISSUE TITLE
Userkey Activities doesn't work anymore

### ISSUE THREAD

**Issue by micnano** [googleapis/google-api-php-client-services#183]
Since yesterday afternoon the function listActivities (
     $ userKey, $ applicationName, $ optParams) returns the following error:
"Invalid string value: 'xxxxxxxxxxxxxxxxxxxxx'. Allowed values: [all, userkey]"

Could it be a google api reports bug?

**Comment by dwsupplee** [comment]
It seems likely this would have been related to the API and potentially the rollout of a new feature (looking back at the history they allowed specifying `all` as a userkey around this time. If you've found this could be specific to the client libraries here, please do let us know and we can re-open.
