### ISSUE TITLE
Some method names don't match their documentation

### ISSUE THREAD

**Issue by GuillaumeRossolini** [googleapis/google-api-php-client-services#184]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: n/a
  - PHP version: v5.4
  - Package name and version: google-api-php-client-services release v0.118

#### Steps to reproduce

  1. Open `Google_Service_AndroidEnterprise`
  2. this object includes a reference to `Google_Service_AndroidEnterprise_Resource_Enterprises`, with a `list` method in the constructor and no `listEnterprises` method
  3. that object does have a `$this->call('list'` in its code, but inside a `listEnterprises()` method not `list()`.

The same happens with :
- `Google_Service_AndroidManagement_Resource_EnterprisesDevices::listEnterprisesDevices()` documented as simply `list()`
- `Google_Service_AndroidManagement_Resource_EnterprisesPolicies::listEnterprisesPolicies()` documented as simply `list()`
- and possibly others, these are the ones I stumbled upon.

If you are worried about backwards compatibility, maybe an alias would help?

**Comment by jdpedrie** [comment]
Certain common words (including "list") are [reserved](https://www.php.net/manual/en/reserved.keywords.php) by PHP. In these cases, it is not possible to create methods which precisely match the API method names. Can you share precisely where you see the PHP client methods documented with incorrect names?

**Comment by GuillaumeRossolini** [comment]
You're completely right.
I was looking at `Google_Service_AndroidEnterprise`, those objects and methods are documented there as the API but not as the PHP methods. I guess there is no real solution for this.

**Comment by jdpedrie** [comment]
We'll try to think about ways in which we can mitigate the issue in the future through better documentation. It might be something we could add to the generator.

**Comment by GuillaumeRossolini** [comment]
@jdpedrie I don't know, this works fine:

```
<?php

class MyClass {
  function list() {
    echo 'test';
  }
}

$obj = new MyClass();
$obj->list();
```

**Comment by jdpedrie** [comment]
> As of PHP 7.0.0 these keywords are allowed as property, constant, and method names of classes, interfaces and traits, except that class may not be used as constant name.

[PHP: List of Keywords](https://www.php.net/manual/en/reserved.keywords.php)

As this client supports PHP >= 5.4, we cannot use a reserved word as a method name.

**Comment by GuillaumeRossolini** [comment]
I know, but would you please allow this method name from php7 onwards? This distinction is allowed on the parent project.

cf. Your link: “As of PHP 7.0.0 these keywords are allowed as property, constant, and method names of classes, interfaces and traits”
