### ISSUE TITLE
Breaking change in Google_Service_SQLAdmin_Resource_Users::delete()

### ISSUE THREAD

**Issue by leonboot** [googleapis/google-api-php-client-services#190]
#### Environment details

  - OS: Linux
  - PHP version: 7.3
  - Package name and version: google/apiclient-services 0.121

The method signature of `Google_Service_SQLAdmin_Resource_Users::delete()` used to have 4 parameters:
* Project ID
* Instance
* Host
* Username

This seems to have been changed recently [in an auto-generated commit](https://github.com/googleapis/google-api-php-client-services/commit/a33fd9ed19fe4e27f2ccebbf45646f38e7cb95af). The last two arguments have been replaced by an `$optParams` argument, which should be an array of optional parameters. It seems the host and username now have to be provided in this array (with the `host` and `name` keys).

There are a number of issues with this change:
* It breaks existing code, which is not to be expected on such a minor version update
* The host and username are far from optional, since this information is crucial to deleting the correct user. So putting them in an array doesn't make any sense.

**Comment by jdpedrie** [comment]
This library contains auto-generated clients which map directly to the Google APIs. That means you can always use the latest version of the clients in your code without waiting for someone to manually update the clients, but it also means it's hard to control for breaking changes.

Outside of development, you should pin `google/apiclient-services` to a specific minor version, and not update that until you've verified that it works.
