### ISSUE TITLE
The Google_Service_People class does not support current parameters

### ISSUE THREAD

**Issue by hkwak** [googleapis/google-api-php-client-services#191]
The implementation of Google_Service_People does not allow to use personFields: 
It is resulting getting (get) unknown parameter: 'personFields' because the definition of methods in Google_Service_People does not include this parameter:

https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/People.php#L92

It only contains requestMask.includeField which is deprecated

**Comment by jdpedrie** [comment]
Try using `Google_Service_PeopleService` instead. I tested and it should work fine for you. Please re-open and let me know if you still have trouble.
