### ISSUE TITLE
Google Classroom API should allow Teacher submit on behalf of Students

### ISSUE THREAD

**Issue by yos1p** [googleapis/google-api-php-client-services#194]
We encounter many cases where we need Teacher need force students to submit their assignments right away. But in the SDK, Google Classroom doesn't allow Teacher to submit students assignment on their behalf.

If students hasn't submit their assignment, when Teacher return and grade their assignment, the API will return error 400 (Failed Precondition check).

**Comment by jdpedrie** [comment]
This forum is only for questions related specifically to the PHP client library. Please review the [How to get help](https://developers.google.com/classroom/support) page for Classroom API, which includes information on feature requests.
