### ISSUE TITLE
GCF metadata v1beta1 deprecation

### ISSUE THREAD

**Issue by scottconnerly** [googleapis/google-api-php-client-services#195]
#### Environment details

  - OS: Linux
  - PHP version: 7.2
  - Package name and version: google/apiclient v2.4.0 which requires this repo (google/apiclient-services) @ "~0.13" which installs version v0.127.

#### Steps to reproduce

  1. Update google/apiclient to latest revision in my project
  2. Still receive emails from GCF telling me I'm using the deprecated endpoints

#### Notes

It doesn't appear that google/apiclient is calling the deprecated endpoint, but it is requiring this package, which is. In several, several classes.

**Comment by danoscarmike** [comment]
@jdpedrie would you mind taking a quick look at this?

**Comment by jdpedrie** [comment]
Hi @scottconnerly,

Could you share a bit more detail about the classes you're using? I don't see any references to v1beta1 in the Cloud Functions client.

We had a similar discussion [here](https://github.com/googleapis/google-api-php-client/issues/1794), perhaps some of the information on tracking down the source of the problem (assuming it isn't from the client library of course) will be useful.

**Comment by scottconnerly** [comment]
Brief investigation:
I just did a `composer init` in an empty directory. Set the only dependency as "google/apiclient" @ version 2.4. Downloaded/installed the packages. Then grepped the vendor folder for "v1beta1".
These files were returned, all in `vendor/google/apiclient-services/src/Google/Service/`
```
Proximitybeacon.php
Clouderrorreporting/Resource/ProjectsGroupStats.php
Clouderrorreporting/Resource/ProjectsEvents.php
AlertCenter.php
Proximitybeacon/Resource/V1beta1.php
FirebaseManagement/Resource/Projects.php
FirebaseManagement/Resource/ProjectsDefaultLocation.php
FirebaseManagement/Resource/ProjectsAvailableLocations.php
AlertCenter/Resource/V1beta1.php
CloudNaturalLanguageAPI.php
DataCatalog.php
CloudPrivateCatalog.php
ServiceDirectory.php
CloudMachineLearning/Resource/ProjectsModels.php
CloudMachineLearning/Resource/ProjectsModelsVersions.php
CloudPrivateCatalogProducer.php
CloudBillingBudget.php
BigQueryConnectionService.php
CloudMachineLearning.php
FirebaseHosting.php
Manager/ReplicaPoolParams.php
NetworkManagement.php
Clouderrorreporting.php
CloudSpeechAPI.php
Replicapoolupdater.php
DataFusion.php
Recommender.php
DataCatalog/Resource/ProjectsLocationsEntryGroupsTags.php
FirebaseManagement.php
Replicapool.php
```
For what it's worth, the one I suspect my project may actually be using is FirebaseManagement/Resource/Projects.php

**Comment by jdpedrie** [comment]
Hi @scottconnerly,

APIs are versioned independently. The Cloud Functions v1beta1 API is being deprecated, but so far as I can tell the Firebase Management v1beta1 API is not. It's quite unlikely that this is the source of your issue. Did you have time to review the information discussed in the issue I linked to above?

**Comment by dwsupplee** [comment]
@scottconnerly if you have any updates here, let us know and feel free to re-open if we can help further.
