### ISSUE TITLE
PHP bindings for Admob API : Need advise to parse Google_Service_AdMob_GenerateMediationReportResponse object returned from mediation.generate

### ISSUE THREAD

**Issue by yusufg-git** [googleapis/google-api-php-client-services#196]
Caveat,  I'm new to the Google OAuth2 and PHP client libraries.  I wanted to consume the Admob Reporting API and kinda figured out how to construct the mediation spec using the PHP bindings for the Admob Service

The documentation here

https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/AdMob/Resource/AccountsMediationReport.php

suggests that the generate method is invokved from the 'mediationReport' member.  However when I do a var_dump($admobService),  it seems that the generate method is to be invoked from the 'accounts_mediationReport' member

Now I can invoke the generate method

```php
$mediationReport = $service->accounts_mediationReport;

$response = new Google_Service_AdMob_GenerateMediationReportResponse;
$response = $mediationReport->generate($name,$request);
```

However, `$response` which should have the methods listed below generates empty strings [eg, `$response->getHeader()`] even though when I do `var_dump($response)`,  the output indicates that the request generated the expected values

https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/AdMob/GenerateMediationReportResponse.php

Any pointers to code examples to help pretty print `$response` would be appreciated

Regards, Yusuf

**Comment by jdpedrie** [comment]
Any class extending `Google_Model` may use `toSimpleObject()` to get a simple representation. In general though, the operation is expensive (cpu wise), so when possible you should use the getters on the response objects.

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
