### ISSUE TITLE
obfuscatedAccountId and obfuscatedProfileId are missing in SubscriptionPurchase model

### ISSUE THREAD

**Issue by yevreinov** [googleapis/google-api-php-client-services#198]
Developer payload has been deprecated and setObfuscatedAccountId() and setObfuscatedProfileId() method has replaced them.

However when executing purchases_subscriptions->get method on server side using google-api-php-client it returns an instance of Google_Service_AndroidPublisher_SubscriptionPurchase which doesn't contain any methods to read obfuscatedAccountId or obfuscatedProfileId.

**Comment by jdpedrie** [comment]
I'm having trouble finding information about this change. Can you share more detail?

**Comment by yevreinov** [comment]
> I'm having trouble finding information about this change. Can you share more detail?

There you go:
https://developer.android.com/google/play/billing/developer-payload

**Comment by emilianocds** [comment]
Is there any solution about it?

**Comment by jdpedrie** [comment]
The clients in this repository are automatically generated based off of specifications published by the teams which manage the APIs. The Android Publisher specification has not been updated to reflect this change. I suggest opening an issue on the [issue tracker](https://issuetracker.google.com/issues?q=componentid:%20190923) to make the team aware of the issue and request the APIs be updated.
