### ISSUE TITLE
How to Refresh Token through a CURL ?

### ISSUE THREAD

**Issue by cullsin** [googleapis/google-api-php-client-services#201]
Hello, 

I am a newbie and I am using Google Calendar API. I have a requirement to arrange a live video conference for my customers. So, I am generating Google Meet URL through an API. 

I have successfully generated an Event Through GIven Example. 

As per example, I need to access the token only through a website. Is it possible to generate an access token on the fly so that the entire process will be automated? 

Or, Is it possible to increase the token refresh time to a longer period. 

Raja K

**Comment by jdpedrie** [comment]
The [Google Calendar Quickstart for PHP](https://developers.google.com/calendar/quickstart/php) has an OAuth sample that demonstrates handling refresh tokens.

**Comment by cullsin** [comment]
Got it. Thanks. I have generated a Hangout Meet URL. How do I restrict the URL to expose only on the event day? Right now, It is available for any time.

**Comment by jdpedrie** [comment]
Please share a code sample of what you're doing now.

**Comment by cullsin** [comment]
Hi, 

Below is the code. I want the Meeting link should be available only on the same day or +/- few hours. How do I restrict that?


                $client = self::getClient();
                $client->setScopes(Google_Service_Calendar::CALENDAR_EVENTS);
                $service = new Google_Service_Calendar($client);

                // Print the next 10 events on the user's calendar.
                $calendarId = 'primary';

                $event = new Google_Service_Calendar_Event([
                        'summary' => 'iChase Online Training Program',
                        'conferenceDataVersion' => 1,
                        'start' => [
                                'dateTime' => $start_time,
                                'timeZone' => 'Asia/Kolkata'],
                        'end' => [
                                'dateTime' => $end_time,
                                'timeZone' => 'Asia/Kolkata']
                        ]);

                $event = $service->events->insert($calendarId, $event);
                $conference = new Google_Service_Calendar_ConferenceData();
                $conferenceRequest = new Google_Service_Calendar_CreateConferenceRequest();
                $conferenceRequest->setRequestId('ichase');
                $conference->setCreateRequest($conferenceRequest);
                $event->setConferenceData($conference);
                $event = $service->events->patch($calendarId, $event->id, $event, ['conferenceDataVersion' => 1]);
                $cs = new CustomerGoogle();
                $cs->meeting_id = $event->id;
                $cs->service_id = $service_id;
                $cs->plain_date = $plain_date;
                $cs->join_url = $event->hangoutLink;
                $cs->save();
                return $event->id;

**Comment by jdpedrie** [comment]
As I said above, after reviewing the [available options](https://developers.google.com/calendar/v3/reference/events#conferenceData) for the conference, I do not believe that is possible. I am not an expert on the Calendar API, and I'm not able to answer your question definitively. Please take a look at the [support](https://developers.google.com/calendar/support) page. You may ask this on Stackoverflow, or if you feel it's a missing feature, on the product issue tracker.
