### ISSUE TITLE
Typical usage comment incorrect for AccountNetworkReport, AccountsMediationReport in admob

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-api-php-client-services#202]
The following issue was reported internally. Filing it here for easier tracking:

The documentation on [this line](https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/AdMob/Resource/AccountsNetworkReport.php#L23) is incorrect, it should be `accounts_networkReport` instead of `networkReport`. There is a similar issue for the [mediation reports](https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/AdMob/Resource/AccountsMediationReport.php#L23).

**Comment by bshaffer** [comment]
fixed in https://github.com/googleapis/google-api-php-client-services/pull/1850
