### ISSUE TITLE
Local Posts Product Type

### ISSUE THREAD

**Issue by socialRanvir** [googleapis/google-api-php-client-services#204]
According to https://developers.google.com/my-business/content/change-log#v42 products were added as a local post type, however, it seems to be missing elsewhere in the documentation and isn't returning in the API?

#### Environment details

  - OS: Ubuntu
  - PHP version: 7.0
  - Package name and version: 4.6

#### Steps to reproduce

  1. n/a

#### Code example

```php
n/a
```

**Comment by jdpedrie** [comment]
My Business is not a part of this repository. You can download the latest revision of the client [here](https://developers.google.com/my-business/samples).
