### ISSUE TITLE
Is it possible to get the distance?

### ISSUE THREAD

**Issue by pjoulot** [googleapis/google-api-php-client-services#208]
I am trying to write a request to get the different activities of the user with the distance.

Is it possible to get the same data as the google fit app?

For each activity/workout
- Activity type (running, etc...)
- Distance done in kilometers

I got something already working for the steps but the different activities seems more tricky since you have to aggregate and the API returns me a denied access everytime I am trying to aggregate on "com.google.distance.delta" telling me the following message:

`Scope not included to read data of type com.google.distance.delta. Possible scopes: https://www.googleapis.com/auth/fitness.location.read, https://www.googleapis.com/auth/fitness.location.write`

But I used this and my app has also those permissions:
```

    $client->addScope(Google_Service_Fitness::FITNESS_ACTIVITY_READ);
    $client->addScope(Google_Service_Fitness::FITNESS_LOCATION_READ);
    $client->addScope(Google_Service_Fitness::FITNESS_LOCATION_WRITE);
```

After digging a lot, I found someone saying that it is not possible to access Location (from entrees you didn't write) since 2018 after an update to increase privacy. Is it true? I am using the Google Fit app and I just want to read the distance not the exact location.

There is my code:

``` 
    $client = new Google_Client();
    $client->setApplicationName('google-fit');
    $client->setAccessType('offline');
    $client->setPrompt('select_account consent');
    $client->setClientId($client_id);
    $client->setClientSecret($client_secret);
    $client->setRedirectUri($redirect_uri);

    $client->addScope(Google_Service_Fitness::FITNESS_ACTIVITY_READ);
    $client->addScope(Google_Service_Fitness::FITNESS_LOCATION_READ);
    $client->addScope(Google_Service_Fitness::FITNESS_LOCATION_WRITE);

    $service = new Google_Service_Fitness($client);

    $datasets = $service->users_dataset;
    $aggBy = new Google_Service_Fitness_AggregateBy();
    $bucketBy = new Google_Service_Fitness_BucketByTime();
    $aggBy->setDataTypeName("com.google.step_count.delta");

    // 2 lines blocking the process.
    $aggBy2 = new Google_Service_Fitness_AggregateBy();
    $aggBy2->setDataTypeName("com.google.distance.delta");

    $bucketBy->setDurationMillis("86400000");
    $aggReq = new Google_Service_Fitness_AggregateRequest();
    $aggReq->startTimeMillis = strtotime("-2 year");
    $aggReq->endTimeMillis = time();
    $aggReq->setAggregateBy([$aggBy, $aggBy2]);
    $aggReq->setBucketByTime($bucketBy);
    $aggregates = $datasets->aggregate('me', $aggReq);
```

Thank you for anybody helping me to figure out what is happening.

PS: I didn't put the whole token part but the app is working to get the total number of steps.

**Comment by jdpedrie** [comment]
According to the [Location data types](https://developers.google.com/fit/datatypes/location) documentation, you may only access location data which was written by your application:

> Note: This data can only be read by the app that wrote the data. Your app can only read back data it wrote. It cannot read location sample data written by other apps.

Please feel free to re-open if you still have questions!

**Comment by pjoulot** [comment]
OK then is it possible to get the number of steps by activity type for the day?
I didn't see any restriction for those in the documentation.

When I set a bucket by time, I get some results but not by Activity.

```
    $aggBy = new Google_Service_Fitness_AggregateBy();
    $bucketBy = new Google_Service_Fitness_BucketByActivity();
    $aggBy->setDataTypeName("com.google.step_count.delta");
    $aggBy->setDataSourceId('derived:com.google.step_count.delta:com.google.android.gms:estimated_steps');
    $bucketBy->setMinDurationMillis("60000");

    $aggReq = new Google_Service_Fitness_AggregateRequest();
    // Put 2 years to be large and get data for testing.
    $aggReq->startTimeMillis = strtotime("-2 year");
    $aggReq->endTimeMillis = time();
    $aggReq->setAggregateBy([$aggBy]);
    $aggReq->setBucketByActivitySegment($bucketBy);
    $aggregates = $datasets->aggregate('me', $aggReq);

    $bucket = $aggregates->getBucket();
```


Is there any example on how to use Google_Service_Fitness_BucketByActivity because I can't get anything working. It is always empty.
