### ISSUE TITLE
v0.279.0 to v0.285.0, getResources() now returns null.

### ISSUE THREAD

**Issue by grasebit** [googleapis/google-api-php-client-services#2099]
After changing the version from v0.279.0 to v0.280.0, getResources() now returns null.

use Google_Service_ShoppingContent.

#### Environment details

  - PHP version: 8.1.12
  - Package name and version: google/apiclient-services v0.280.0

#### Code example

```php
# example

    $params = ['maxResults' => 100];
    $service = new \Google_Service_ShoppingContent($client);
    $response = $service->productstatuses->listProductstatuses($this->merchant_center_id, $params);

    foreach ($response->getResources() as $resource) {
        //  $response->getResources() is null
        //  error message : foreach() argument must be of type array|object, null given
    }
```

v0.279.0

![v0 279 0](https://user-images.githubusercontent.com/6274389/210028935-8585484f-9cf2-49e1-bd29-f5b0b1eb8f8d.png)

v0.280.0

![v0 280 0](https://user-images.githubusercontent.com/6274389/210028937-6efe1f93-5456-4a93-8890-486103f498ec.png)

v0.280.0 error

![v0 280 0_2](https://user-images.githubusercontent.com/6274389/210028943-c6b825f0-ef6f-4158-a4a5-9690feacc986.png)

Thanks!

**Comment by jacekkarczmarczyk** [comment]
There might be the same issue for multiple other services. Ex. `\Google\Service\Firestore\Document::getFields()` used to return array, now it returns null:

Following test case passes in 0.279 but fails in 0.280
```php
    public function testDocument() {
        $document = new \Google\Service\Firestore\Document();
        $this->assertIsArray($document->getFields());
    }
```

It's not only a problem with changed behavior, also the phpdoc are wrong - it still shows that `getFields` returns and array: https://github.com/googleapis/google-api-php-client-services/blob/main/src/Firestore/Document.php#L60, which makes it not possible to find the issue with static code analysers

**Comment by grasebit** [comment]
Same for v0.284.0

**Comment by grasebit** [comment]
Same for v0.285.0

**Comment by fieteboerner** [comment]
We encountered the exact same problem with the gmail api. We can can also confirm that `v0.279.0` is the last version which returns empty arrays instead of null values.

@googleapis-publisher can you confirm if this is a bug and you are on it?

**Comment by bshaffer** [comment]
This is most likely a result of this PR: https://github.com/googleapis/google-api-php-client-services/pull/1836/files

But this is confusing to me, as all the PR did was add properties which were previously being created dynamically (to fix PHP 8.2 errors). This should not have altered existing behavior.

**Comment by bshaffer** [comment]
On a side note, @jacekkarczmarczyk you will have a much better time if you use the [Google Cloud Firestore library](https://github.com/googleapis/google-cloud-php-firestore) (`google/cloud-firestore`) instead

**Comment by jacekkarczmarczyk** [comment]
> On a side note, @jacekkarczmarczyk you will have a much better time if you use the [Google Cloud Firestore library](https://github.com/googleapis/google-cloud-php-firestore) (`google/cloud-firestore`) instead

Thank you for the suggestion, unfortunately it requires gRPC which I can't use on my server

**Comment by bshaffer** [comment]
Looking more into this, the `Google\Model` class uses the magic method `__get` to dynamically set fields to `[]` if there is a corresponding `$xyzDatType = 'array'` on the object. When I added the properties in #1836, this bypasses the dynamic `__get` method.

**Comment by grasebit** [comment]
@jacekkarczmarczyk Thank you.
