### ISSUE TITLE
Resource is a other reserved keyword

### ISSUE THREAD

**Issue by robindevitt** [googleapis/google-api-php-client-services#2107]
`Resource` is now a [other reserved keyword](https://www.php.net/manual/en/reserved.other-reserved-words.php) within PHP, so it throws errors that it shouldn't be used.

Example files ( full gist further down ):

- https://github.com/googleapis/google-api-php-client-services/blob/main/src/GoogleAnalyticsAdmin/Resource/PropertiesWebDataStreams.php
- https://github.com/googleapis/google-api-php-client-services/blob/main/src/GoogleAnalyticsAdmin/Resource/PropertiesDataStreamsMeasurementProtocolSecrets.php

```
FILE: https://github.com/googleapis/google-api-php-client-services/blob/main/src/GoogleAnalyticsAdmin/Resource/PropertiesConversionEvents.php
---------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------
 18 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
---------------------------------------------------------------------------------------------------------------------------------------------------
```

```
FILE: https://github.com/googleapis/google-api-php-client-services/blob/main/src/GoogleAnalyticsAdmin/Resource/PropertiesFirebaseLinks.php
------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------
 18 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
------------------------------------------------------------------------------------------------------------------------------------------------
```

#### Environment details
  - PHP version: 7.4 & 8.1

I originally posted this issue to the Google Site Kit WP Plugin, which they directed me to here, reference - https://github.com/google/site-kit-wp/issues/6125

The warnings occur when using PHP_CodeSniffer:
```
./vendor/bin/phpcs -p --standard=PHPCompatibility \
  --runtime-set testVersion 7.4 \
  --extensions=php \
  -d memory_limit=1G \ .
```

I have a GIST of all warnings - https://gist.github.com/robindevitt/c913b2b8e25be4303aaa0a27b44ff2c1 which was run in the mentioned plugin, these warning are all relevant to this issue, let me know if I should adjust the

**Comment by vishwarajanand** [comment]
Hi @robindevitt , thanks for reporting this issue. 
Existence of `Resource` in codebase is not throwing any runtime error(s) in even the latest php8.2, and it seems the impact is limited to lint errors on this repo as per your GIST. Its use is also permitted on [the PHP doc](https://www.php.net/manual/en/reserved.other-reserved-words.php#:~:text=Whilst%20they%20may%20still%20be%20used%20as%20class%2C%20interface%2C%20and%20trait%20names%20(as%20well%20as%20in%20namespaces)%2C). The fix would also involve changing a bunch of classes and might be breaking for a lot of users. 
At this point, we are reluctant to make a fix, but will surely consider this later.
