### ISSUE TITLE
GenerateMediationReportResponse result parsing 

### ISSUE THREAD

**Issue by dtiwar** [googleapis/google-api-php-client-services#214]
Admob - How do we parse the GenerateMediationReportResponse in python? do we have any method?

**Comment by bshaffer** [comment]
This repository is for PHP and not python. Please submit your questions here: 
https://github.com/googleapis/google-api-python-client/issues

**Comment by dtiwar** [comment]
> This repository is for PHP and not python. Please submit your questions here:
> https://github.com/googleapis/google-api-python-client/issues

Thank you
