### ISSUE TITLE
v1 of Google API PHP Client - Throwing error, not allwoing to create a project in Google Cloud console.

### ISSUE THREAD

**Issue by phpdevelopernk-git** [googleapis/google-api-php-client-services#216]
I am trying to create a project in the Google console cloud using the PHP client library.
I copied this sample code from https://cloud.google.com/resource-manager/reference/rest/v1/projects/create#php

**Steps taken/ Got the issue:**

 1. This line " `$requestBody = new \Google_Service_CloudResourceManager_Project();` ".

	**Throwing error** : 'Class Google_Service_CloudResourceManager_Project not found'.

	Then I checked in the "[Try this API][1]" menu, we can pass the JSON to API with Google API Explorer. I tested with Google API Explorer and the results are working fine. ([See screenshot][1])

 2. Commenting this line "`$requestBody = new \Google_Service_CloudResourceManager_Project();`"
	and trying to pass the json required to create method ( as i have checked in "[Try this API][1]" menu).
    
    **Throwing error** :  Call to a member function `create()` on null at this line "`$response = $service->projects->create($requestBody);`".

**My Google OAuth script is working fine, the only issue with this project create script**

**PHP Script:**

```
$client = new \Google_Client();
$client->setApplicationName('Google-CloudResourceManagerSample/0.1');
//$client->useApplicationDefaultCredentials();
$client->addScope('https://www.googleapis.com/auth/cloud-platform');

$service = new \Google_Service_CloudResourceManager($client);

// TODO: Assign values to desired properties of `requestBody`:

//$requestBody = new Google_Service_CloudResourceManager_Project();

$requestBody = '{
				  "name": "bob kris project 2",
				  "projectId": "bk-project-290016"
				}';

$response = $service->projects->create($requestBody);

// TODO: Change code below to process the `response` object:
echo '<pre>', var_export($response, true), '</pre>', "\n";

die;
```

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Kh4Cy.png

**Comment by jdpedrie** [comment]
[`v0.50.0`](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.50) is the last version of this client which supported v1 of the Resource Manager API. That version will still work with the API Client, though if you are using multiple APIs, it is very likely that there will be breaks, and any changes in the Resource Manager v1 API since then will not be reflected in the client.

Your best bet in this case is likely to construct and send the HTTP requests yourself using Guzzle. The [README](https://github.com/googleapis/google-auth-library-php#call-the-apis) for `google/auth` contains a sample of how you can create an authenticated Guzzle client.

**Comment by phpdevelopernk-git** [comment]
@jdpedrie thanks for your reply. but my google auth is working fine and no issue, even with this auth I am fetching keywords via google ads API. but when using this https://cloud.google.com/resource-manager/reference/rest/v1/projects/create#php API, I am getting an issue, so I don't think I need to change the way to call auth API via Guzzle client.

**Comment by phpdevelopernk-git** [comment]
Any update ?

**Comment by jdpedrie** [comment]
If you are using other services, it's unlikely that you'll be able to downgrade `google/apiclient-services` to `v0.50.0`. This library only provides a single version of each service, and is not able to support the resource manager v1 API. This is the reason I suggested using an authorized HTTP client to interact directly with the resource manager API. That is the only way you'll avoid requiring a very old and out-of-date dependency.

**Comment by jeffersonmartin** [comment]
@jdpedrie I'm running into this same issue.

Why does the Resource Manager API v2 only include folders and not include the organizations, projects, etc that were in v1? It seems like we lost a lot of functionality here.

**Comment by jdpedrie** [comment]
Unfortunately I don't have any more information on the reasoning behind that decision than you do.

**Comment by dwsupplee** [comment]
The client library only supports the latest major version of a given service, unfortunately. While not ideal, a good path forward would be to give the generator we use to create these files a shot and attempt to create the files needed to interact with the V1 service yourself: https://github.com/googleapis/google-api-php-client-services/tree/master/generator 

Hope it helps!
