### ISSUE TITLE
Analytics documentation?

### ISSUE THREAD

**Issue by zachleigh** [googleapis/google-api-php-client-services#218]
I'm looking for a full list of possible values for Google_Service_AnalyticsReporting_DimensionFilter::setOperator but can not find it anywhere. I'm having a hared time finding documentation in general for this library. Is there official documentation anywhere besides the quick start guide?

**Comment by jdpedrie** [comment]
You can find the list of possible values [here](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#Operator). The API clients themselves generally don't have their own documentation, however they are (almost) one-to-one with the API reference documentation. So you can use the API reference, as linked above, to find detailed (and up-to-date) information on the APIs themselves.

**Comment by zachleigh** [comment]
Thanks @jdpedrie. Thats just what I was looking for.
