### ISSUE TITLE
YouTube API detailed error messages.

### ISSUE THREAD

**Issue by IORoot** [googleapis/google-api-php-client-services#219]
Hey there, I seem to only be able to get very generic error messages back from the YouTube API and can't seem to figure out if there is a configuration problem or not.

I've enabled the `api_format_2` on the `google-api-php-client` object using the `$this->client->setApiFormatV2(TRUE);` method, and my requests are going through, AND I'm able to do what I need to do on YouTube.

However, there are times when some input is wrong (Uploading a video for instance - took me forever to figure out that a hard limit of 70 characters on the title was causing an error like this:
```
{"error": {"code": 400,"message": "Request contains an invalid argument.","errors": [{"message": "Request contains an invalid argument.","domain": "global","reason": "badRequest"}],"status": "INVALID_ARGUMENT"}}
```

Which does not mention any details on where to look. Which argument? Why is it invalid?

All of my requests are in `try { } catch { }` blocks with the correct `catch (\Google_Service_Exception $e) { }` exceptions, which are being caught correctly. I've even got XDebug looking at the exception and there isn't anything coming back from YouTube with more detail.

Is there any way to enable better error reports / messaging at all?

Thanks!

**Comment by dwsupplee** [comment]
It sounds like you're doing everything right from the perspective of error handling on your end. Unfortunately, there isn't a way to enable more granular errors from the API itself. The best route to get some traction on this front would likely be to try and reach out to the [YouTube team's support](https://developers.google.com/youtube/v3/live/support) to try and get it more clearly on their radar.
