### ISSUE TITLE
Upload a photo with "updateContactPhoto"

### ISSUE THREAD

**Issue by NazgulTuga** [googleapis/google-api-php-client-services#220]
How does the function "updateContactPhoto", from the class "Google_Service_PeopleService_Resource_People", works?
How can i upload a photo?

**Comment by jdpedrie** [comment]
As described in the [API documentation](https://developers.google.com/people/api/rest/v1/people/updateContactPhoto#request-body), `photoBytes` is a base64-encoded string of raw bytes.

```php
$service->people->updateContactPhoto($name, new Google_Service_PeopleService_UpdateContactPhotoRequest([
    'photoBytes' => base64_encode(file_get_contents('/path/to/photo.jpg'))
]));
```

**Comment by NazgulTuga** [comment]
How do I initiate the variables "$service"?

**Comment by bizmate** [comment]
by looking at the documentation https://developers.google.com/people/quickstart/php 1 minute google search
```
$client = getClient();
$service = new Google_Service_PeopleService($client);
```
