### ISSUE TITLE
Calendar API Patch Removes All Other Properties

### ISSUE THREAD

**Issue by satezmedia** [googleapis/google-api-php-client-services#2350]
When we try to patch only event description it removes all other properties like attendees, recurrence etc.

This is probably caused by recent release where array properties have empty array by default.
In patch this means it will remove all attendees.

"Array fields, if specified, overwrite the existing arrays; this discards any previous array elements." - [Docs for patch](https://developers.google.com/calendar/api/v3/reference/events/patch)

  - PHP version: 8.2
  - Package name and version:  v0.289.1

#### Code example

```php
        $eventPatch = new Event();
        $eventPatch->description = 'test';

        $calendarService = new Google_Service_Calendar($client);
        $calendarService->events->patch($calendarId, $eventId, $eventPatch);

```

**Comment by christophmayrhofer** [comment]
This should have been a major version bump (breaking change). Right now everyone is potentially affected by running 
composer update

**Comment by christophmayrhofer** [comment]
@bshaffer 
@jacekkarczmarczyk

**Comment by parallels999** [comment]
https://github.com/googleapis/google-api-php-client-services/pull/2348 ??

**Comment by bshaffer** [comment]
Please update to the latest versions of `google/apiclient` (v2.13.1) and `google/apiclient-services` (v0.290.1) to fix this issue
