### ISSUE TITLE
Missing projects_serviceAccounts and projects_serviceAccounts_keys properties from Google\Service\Iam

### ISSUE THREAD

**Issue by leonboot** [googleapis/google-api-php-client-services#2439]
#### Environment details

  - OS: N/A
  - PHP version: 8.1
  - Package name and version: google/apiclient-services 0.290.1

The following code used to work, and if I translate from the [Java/Go examples in the documentation](https://cloud.google.com/iam/docs/service-accounts-create#iam-service-accounts-create-go) correctly, should still work:

```php
/** @var Google\Client $myGoogleClient */
$svc = new Iam($myGoogleClient);

$accountRequest = new CreateServiceAccountRequest();
$accountRequest->setAccountId('some-service-account');
$account = $svc->projects_serviceAccounts->create('projects/my-project-12345', $accountRequest);

$keyRequest = new CreateServiceAccountKeyRequest();
$keyRequest->setPrivateKeyType('TYPE_GOOGLE_CREDENTIALS_FILE');
$key = $svc->projects_serviceAccounts_keys->create('projects/my-project-12345/serviceAccounts/'.$account->getUniqueId(), $keyRequest);
```

However, it seems both the `projects_serviceAccounts` and `projects_serviceAccounts_keys` properties, which should contain an instance of Google\Service\Iam\Resource\ProjectsServiceAccounts` and `Google\Service\Iam\Resource\ProjectsServiceAccountsKeys` respectively, have disappeared. I searched the code to find out if these properties had been moved to another service, but the only usages of these classes were in the corresponding files themselves. We now have no automated means of creating service accounts anymore.

**Comment by anatolii-cordial** [comment]
It was removed in version v0.286.0

**Comment by leonboot** [comment]
Indeed, fixing the library to `v0.285.0` in composer.json circumvents the issue; it's the last version to contain the IAMv1 API classes. It sounds plausible it was disabled by accident in the code generation process; it would make sense to disable an old version of an API, but not before the latest version has reached feature parity with the previous version. This is by far not the case with IAMv2.

**Comment by saranshdhingra** [comment]
Thanks for bringing this to our attention and thanks for your patience.

Let me discuss this and get back to you with a recommended alternative, or with the information of the missing parameters.

**Comment by saranshdhingra** [comment]
So, I got to know that we can't really support multiple API versions for a product in `google-api-client` repository.
So, when the Iam product starts _preferring_ the version v2, it gets replaced in our package as well.

The 2 alternatives that I have:
1. As already noted, pin the library version to `v0.285.0` in `composer.json` and use the code as-is.
2. Use the `authorize` method on the `$client` and call the post request with the http client instead. This would look like this:
```php
// After your usual authentication process
$httpClient = $client->authorize();
$projectName = "...";
$serviceAccountId = "...";
$url = "https://iam.googleapis.com/v1/projects/$projectName/serviceAccounts";
$response = $httpClient->post($url, [
    'form_params' => [
        'accountId' => $serviceAccountId
    ]
]);

$jsonResponse = $response->getBody()->getContents();
```

An advantage is that you still get updates for the library. Obviously the tradeoff being that this snippet isn't the best developer experience.

If I find better solutions I'll certainly add them here, but for now this is what I have.
I'll be closing this for now, but please reopen this if needed.

Regards,

**Comment by leonboot** [comment]
Does Google have any intent on attaining feature parity between IAMv2 and IAMv1? It seems v2 only supports policies, which is a fraction of the object types supported by v1 (https://cloud.google.com/iam/docs/reference/rest). It seems like a strange decision to me to supersede an API, dropping support for the previous version, while the API hardly offers the same features as the preceded version.
