### ISSUE TITLE
Photos Library Service?

### ISSUE THREAD

**Issue by meisemann1999** [googleapis/google-api-php-client-services#2664]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Reading through some older documentation, it seems that Google_Service_PhotosLibrary used to be part of the google-api-php-client package before the services were split off into this one. Now, when I try to include "PhotosLibrary" in the composer.json file as part of the "extra" parameter, which I am using to whitelist certain services, Composer throws an error that it does not exist. I have also looked through all the Services files and can't find anything. Has this been left out in favor of the photos-library package?

**Comment by saranshdhingra** [comment]
Hi @meisemann1999 
Could you please point me to the documentation that refers `Google_Service_PhotosLibrary`?

Thanks.

**Comment by meisemann1999** [comment]
I could not find specific documentation, but looking through old releases, it seems that the PhotosLibrary folder and PhotosLibrary.php were removed in v0.200.0 without mention in the release notes. v0.181.0 contains both; v0.200.0 does not.

https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.181.0

https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.200.0

**Comment by saranshdhingra** [comment]
Hi @meisemann1999 
Thanks for the clarification.

I see that the photos library has moved to it's own [package](https://github.com/google/php-photoslibrary).
So, you can just browse the installation instructions in that repo and you should be able to access the library easily.

As per why it wasn't included in the release notes, would be difficult to say now.
We try to be verbose with our release notes right now.

But thanks for keeping us in check :)
