### ISSUE TITLE
BusinessProfilePerformance: Google \ Exception (fetchMultiDailyMetricsTimeSeries) unknown parameter: 'dailyRange'

### ISSUE THREAD

**Issue by nekromoff** [googleapis/google-api-php-client-services#2681]
Error fetching multiday time series.

`dailyRange` is a documented object, part of the required params:
https://developers.google.com/my-business/reference/performance/rest/v1/locations/fetchMultiDailyMetricsTimeSeries
https://developers.google.com/my-business/reference/performance/rest/v1/DailyRange

#### Environment details

  - OS: Linux
  - PHP version: 8.2
  - Package name and version: 

#### Steps to reproduce

  1.Run fetchMultiDailyMetricsTimeSeries function

#### Code example

```php
$metrics = [
            'BUSINESS_IMPRESSIONS_DESKTOP_MAPS',
            'BUSINESS_IMPRESSIONS_DESKTOP_SEARCH',
            'BUSINESS_IMPRESSIONS_MOBILE_MAPS',
            'BUSINESS_IMPRESSIONS_MOBILE_SEARCH',
            'BUSINESS_CONVERSATIONS',
            'BUSINESS_DIRECTION_REQUESTS',
            'CALL_CLICKS',
            'WEBSITE_CLICKS',
            'BUSINESS_BOOKINGS',
            'BUSINESS_FOOD_ORDERS',
            'BUSINESS_FOOD_MENU_CLICKS',
        ];
$range = new \stdClass();
        $range->startDate = new \stdClass();
        $range->endDate = new \stdClass();
        $start = '3 days ago 00:00:00';
        $range->startDate->year = Carbon::parse($start)->format('Y');
        $range->startDate->month = Carbon::parse($start)->format('m');
        $range->startDate->day = Carbon::parse($start)->format('d');
        $end = '2 days ago 00:00:00';
        $range->endDate->year = Carbon::parse($end)->format('Y');
        $range->endDate->month = Carbon::parse($end)->format('m');
        $range->endDate->day = Carbon::parse($end)->format('d');
$params = ['dailyMetrics' => $metrics, 'dailyRange' => $range];
                $this->gbp_performance->locations->fetchMultiDailyMetricsTimeSeries($location->name, $params);
```

**Comment by sheriffmarley** [comment]
Had the same issue. You need to pass the dailyRanges as strings, like

```php
 $query = [
                'dailyMetrics' => ['WEBSITE_CLICKS', 'CALL_CLICKS'],
                'dailyRange.startDate.year' => 2022,
                'dailyRange.startDate.month' => 1,
                'dailyRange.startDate.day' => 1,
                'dailyRange.endDate.year' => 2022,
                'dailyRange.endDate.month' => 3,
                'dailyRange.endDate.day' => 31,
];

```

**Comment by bshaffer** [comment]
I agree this is confusing - but I do not think it's the fault of the client library. The [discovery doc](https://businessprofileperformance.googleapis.com/$discovery/rest?version=v1) shows the same parameters that we have documented in the method signature:

**The BusinessProfilePerformance Discovery Doc:**

<img width="658" alt="Screenshot 2023-09-08 at 9 33 01 AM" src="https://github.com/googleapis/google-api-php-client-services/assets/103941/ac83ed14-a3c4-4eaa-a497-fe6ba1083c0f">

**The method params documented by this library**:

https://github.com/googleapis/google-api-php-client-services/blob/168a77774693ce5f0626bfc50af0f8ad3e6e4357/src/BusinessProfilePerformance/Resource/Locations.php#L33-L58

I don't know why the documentation has an object `DailyRange`, which doesn't exist. But either way, if you look at the [Making Requests](https://github.com/googleapis/google-api-php-client#making-requests) section of the README, there are several formats which will work for making requests, but using `stdClass` is not supported (as you have done in your code example). 

I hope this helps. It seems like this library's documentation is correct, but the documentation for the API itself is a bit confusing.
