### ISSUE TITLE
HangoutsChat - Cannot add user into a space

### ISSUE THREAD

**Issue by lekiend** [googleapis/google-api-php-client-services#2905]
Hello,

I try to setup a HangoutsChat space with me & 1 additional user.
I always get the following error {"error": {"code": 400,"message": "**Missing or malformed user resource name in the request. Human user resource name must follow this format: users/{user}. App user resource name must be set as users/app.**"

Here is my code. I can not find why it doesn't work.

```
$gg_chat_email = "example@gmail.com";
$people = new Google\Service\PeopleService( $client );
$person = new Google\Service\PeopleService\Person(["emailAddresses" => [["value" => $gg_chat_email]]]);
$person = $people->people->createContact($person);
$resourceName = $person->resourceName;
// OK, person is created and resourceName is correct.

$hangoutsChat = new Google\Service\HangoutsChat( $client );
$space = new Google\Service\HangoutsChat\Space(["displayName" => "My space", "spaceType" => "SPACE"]);
$resourceName = str_replace( "people", "users", $resourceName );
$membership1 = new Google\Service\HangoutsChat\Membership(["member" => ["name" => $resourceName, "type" => "HUMAN"]] );
$SetUpSpaceRequest = new Google\Service\HangoutsChat\SetUpSpaceRequest(["space" => $space, "memberships" => [$membership1]]);
$space = $hangoutsChat->spaces->setup( $SetUpSpaceRequest );
```

Thank you for your help.
Dimitri

**Comment by saranshdhingra** [comment]
Hi @lekiend 
The error that you have mentioned seems like an incorrect people resource name.

I tried the code snippet as such:
```
function addPersonInExistingHangoutSpace($client) {
    $userId = ""; // people resource id like 100000033......
    $service = new HangoutsChat($client);
    $space = new Google\Service\HangoutsChat\Space(["displayName" => "My space", "spaceType" => "SPACE"]);
    $membership1 = new Google\Service\HangoutsChat\Membership(["member" => ["name" => "users/$userId", "type" => "HUMAN"]] );
    $SetUpSpaceRequest = new Google\Service\HangoutsChat\SetUpSpaceRequest(["space" => $space, "memberships" => [$membership1]]);
    $space = $service->spaces->setup( $SetUpSpaceRequest );
}
```

This created the space and added the person to space.

One thing to note here is that the user is in my contacts. Please confirm if this is the case or not.

**Comment by lekiend** [comment]
Hello,

In the first part of my code, $resourceName is returned correctly. I just replace "people" with "users" to fit the documentation.
Anyway, I discover that it is possible only with internal users. It is not possible to use the Chat API with external users.

Beacause thos restrictions, I moved to Telegram chat with less restrictions and a lot easier to use.

Regards
