### ISSUE TITLE
Cant update Firebase Remote config using SDK as there is no way to set headers

### ISSUE THREAD

**Issue by chasen** [googleapis/google-api-php-client-services#309]
There doesnt seem to be any way to set needed headers using the SDK to update the firebase remote config. In order to update the config you need to specify the "If-Match" header using the latest eTag from the getRemoteConfig call or "*" to force overwriting. However based on the code for this, it just doesnt seem possible.

#### Environment details

  - OS: docker - debian:buster-slim
  - PHP version: 7.4-fpm
  - Package name and version: "google/apiclient": "^2.7"

#### Steps to reproduce

  1. Ensure that a service account is setup for your project
  2. try to update your config with the code below
  3. Fail because there is no way to set or modify the headers needed, specifically "If-Match"

#### Code example

```php
    $client = new \Google_Client();
    $client->useApplicationDefaultCredentials();
    $client->addScope('https://www.googleapis.com/auth/firebase.remoteconfig');
    $client->fetchAccessTokenWithAssertion();
    $firebase = new \Google_Service_FirebaseRemoteConfig($client);
    $remoteConfig = $firebase->projects->getRemoteConfig($this->firebase_project_id);
    // Update remote config as needed
    $resp = $firebase->projects->updateRemoteConfig($this->firebase_project_id, $remoteConfig, ['validateOnly' => true]);
    // returns "[VERSION_MISMATCH]: No If-Match header found on UpdateRemoteConfig call"
```

**Comment by dwsupplee** [comment]
It is a little bit wonky as this isn't built right into the client, but you should be able to set some headers using 

```
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
```
