### ISSUE TITLE
CloudResourceManager client is missing classes for all API methods except these for version 3

### ISSUE THREAD

**Issue by slash686** [googleapis/google-api-php-client-services#314]
In the docs of CloudResourceManager API located [here](https://cloud.google.com/resource-manager/reference/rest/v1/projects/create), the following code sample is listed:
```php
<?php
/*
 * BEFORE RUNNING:
 * ---------------
 * 1. If not already done, enable the Cloud Resource Manager API
 *    and check the quota for your project at
 *    https://console.developers.google.com/apis/api/cloudresourcemanager
 * 2. This sample uses Application Default Credentials for authentication.
 *    If not already done, install the gcloud CLI from
 *    https://cloud.google.com/sdk and run
 *    `gcloud beta auth application-default login`.
 *    For more information, see
 *    https://developers.google.com/identity/protocols/application-default-credentials
 * 3. Install the PHP client library with Composer. Check installation
 *    instructions at https://github.com/google/google-api-php-client.
 */

// Autoload Composer.
require_once __DIR__ . '/vendor/autoload.php';

$client = new Google_Client();
$client->setApplicationName('Google-CloudResourceManagerSample/0.1');
$client->useApplicationDefaultCredentials();
$client->addScope('https://www.googleapis.com/auth/cloud-platform');

$service = new Google_Service_CloudResourceManager($client);

$optParams = [];

do {
  $response = $service->projects->listProjects($optParams);

  foreach ($response['projects'] as $project) {
    // TODO: Change code below to process each `project` resource:
    echo '<pre>', var_export($project, true), '</pre>', "\n";
  }

  $optParams['pageToken'] = $response->getNextPageToken();
} while ($optParams['pageToken']);
?>
```

Running this code yields:
`Class Google_Service_CloudResourceManager_Project not found`

It seems that **only CloudResourceManager API **v3**** methods are present in the package - all of v1 & v2 sources are missing. AFAIK these classes should be auto-generated on build step of some Google-internal tool, so it is possible that the problem lies in the aforementioned tool.

Thanks!

**Comment by bshaffer** [comment]
Yes, this client library unfortunately only generates the most recent version for each API. Past versions can be pulled in by requesting a specific version of the `google/apiclient-services` package.

**Comment by bshaffer** [comment]
I believe we need to add a warning for these earlier docs to say that the clients do not exist. To use this client library, you'll need to use [v3](https://cloud.google.com/resource-manager/reference/rest/v3/tagBindings/create) instead. 

You can also make HTTP calls directly using REST/JSON. See [google/auth](https://github.com/googleapis/google-auth-library-php#call-the-apis) for examples of how to do this.

Closing this issue as it's (unfortunately) WAD.  I will open a bug internally to update the invalid samples in our API documentation.
