### ISSUE TITLE
composer install fails while trying to download "google/apiclient-services" everytime for the last three weeks

### ISSUE THREAD

**Issue by psycho3069** [googleapis/google-api-php-client-services#3273]
This is the cmd-cli error response while trying to run "composer install":

> Install of google/apiclient-services failed
> The following exception is caused by a process timeout
> Check https://getcomposer.org/doc/06-config.md#process-timeout for details
> 
> In Process.php line 1204:
> 
>   The process ""C:\Program Files\7-Zip\7z.EXE" x -bb0 -y C:\laragon\www\plots_sale\vendor\composer\tmp-bacca6210c59da
>   91ad77347d7aa005cd -oC:\laragon\www\plots_sale\vendor\composer\0ea8019e" exceeded the timeout of 300 seconds.

![composer-install-error-for-google-applicant-services](https://github.com/googleapis/google-api-php-client-services/assets/33130889/a524a034-157f-4922-a8d0-637210a80ce5)

**Comment by fremantle-matt** [comment]
Same. I think the library is too big....

**Comment by warm--tape** [comment]
Same issue here

**Comment by ajupazhamayil** [comment]
It works for me now, are you still facing this issue?

**Comment by psycho3069** [comment]
Yes, still facing the same @ajupazhamayil

**Comment by yash30201** [comment]
It seems like this issue is arising due to the default timeout present there in Composer. Please see [this](https://getcomposer.org/doc/06-config.md#process-timeout) reference for increasing the process timeout value.

This should solve this issue. Please re-open if it still exists.

**Comment by bshaffer** [comment]
This is a potential solution: https://github.com/googleapis/google-api-php-client-services/pull/1730
