### ISSUE TITLE
Google Sheets - batchUpdate - PasteDataRequest - corrupted data when sheet filter applied

### ISSUE THREAD

**Issue by tartakxg** [googleapis/google-api-php-client-services#329]
- OS: Debian 10
  - PHP version: 7.4
  - Package name and version: google/apiclient-services v0.165.0

#### Steps to reproduce

  1. Apply basic filter on sheet
  ![Screenshot_3](https://user-images.githubusercontent.com/8146351/112374011-44d55680-8cea-11eb-97fa-966a128a8dac.png)

  2. Filter by age 24  
![Screenshot_4](https://user-images.githubusercontent.com/8146351/112374014-456ded00-8cea-11eb-9d3f-420e25fbbb28.png)

3. Run API bacthUpdate to set Alex phone to "XXX". But result of request - updated Anna phone.
![Screenshot_5](https://user-images.githubusercontent.com/8146351/112374016-46068380-8cea-11eb-96ac-2957b859b1d9.png)
![Screenshot_6](https://user-images.githubusercontent.com/8146351/112374017-46068380-8cea-11eb-8202-e2cb45f22538.png)

#### Code example

```php
$requests = [
    [
	    "pasteData"=> [
	    	"data"=> "XXX",
	    	"coordinate"=> [
		        "rowIndex"=> 2,
		        "columnIndex"=> 2,
		        "sheetId"=> 778703494,
	      	],
	      	"delimiter"=> ";"
	    ]
	],
];
$requestBody = new Google_Service_Sheets_BatchUpdateSpreadsheetRequest();
$requestBody->setRequests($requests);
$response = $service->spreadsheets->batchUpdate($spreadsheetId, $requestBody);
```

**Comment by jdpedrie** [comment]
Hi @tartakxg,

Unfortunately we can only offer support for issues specific to the clients. It appears this is either a usage issue or a bug in the API itself. For those questions, we advise referring to the [support reference](https://developers.google.com/sheets/api/support) for options on getting help from people with specific expertise in the Sheets API.
