### ISSUE TITLE
Autoload Psr-0 issue on Composer 2.x

### ISSUE THREAD

**Issue by sangnguyenplus** [googleapis/google-api-php-client-services#331]
Composer warning when installing the latest version.

#### Environment details

  - OS: MacOS Big Sur
  - PHP version: 7.4
  - Package name and version: v0.170.0

#### Steps to reproduce

  `composer update`

<img width="1214" alt="Screen Shot 2021-04-21 at 11 08 55 AM" src="https://user-images.githubusercontent.com/6972407/115495598-369b3b80-a292-11eb-951f-2eb702ddda53.png">

Folder `/vendor/google/apiclient-services/src/Google/Service/AdSense` is skipped so we can't use it.

It's better if we can upgrade source code to follow Psr-4 autoloading standard as https://github.com/googleapis/google-api-php-client/

Please check and correct it.
Thanks!

**Comment by alex-patterson-webdev** [comment]
I have manually added the previous version of google/apiclient-services which is `v0.169.0` that has solved the issue for now

"google/apiclient": "2.9.1",
"google/apiclient-services" : "v0.169.0" <-- added to composer.json

**Comment by sangnguyenplus** [comment]
@alex-patterson-webdev Yes, it's a good temporary solution.

**Comment by jdpedrie** [comment]
Thanks for the report! We're tracking this issue here: https://github.com/googleapis/google-api-php-client/issues/2073, so I'm going to close this to consolidate things.
