### ISSUE TITLE
Google_Service_YouTube_VideoSnippet needs "embeddable" -- but does the API work?

### ISSUE THREAD

**Issue by ianring** [googleapis/google-api-php-client-services#334]
The "allow embedding" property of a YouTube VideoSnippet is absent from the client; I added it to my own fork but I'm not confident that Google is even respecting it, despite that the property exists in some of the documentation.

**Comment by saranshdhingra** [comment]
Hi @ianring 
Apologies for the delayed response on this issue.

I tried the following code snippet:
```
$service = new Youtube($client);
$result = $service->search->listSearch("snippet",[
    'type' => 'video',
    'videoEmbeddable' => true,
    'q' => 'php'
]);

foreach($result->getItems() as $item) {
    echo $item->getSnippet()->getTitle();
}
```

And I got the same result as I got when I used the [search:list](https://developers.google.com/youtube/v3/docs/search/list) method from the reference.

Please note that the documentation for `videoEmbeddable` mentions:
> If you specify a value for this parameter, you must also set the [type](https://developers.google.com/youtube/v3/docs/search/list#type) parameter's value to video.

Hopefully that was what was missing when you tried the request.

I'll be closing this issue for now, but if something doesn't add up or if you have more questions regarding this, please feel free to reopen this.

Thanks.
