### ISSUE TITLE
when only Update the privacy status of the video, we get the Embeddable option to be reset to false 

### ISSUE THREAD

**Issue by XuruDragon** [googleapis/google-api-php-client-services#354]
#### Information

We have a video which has already set in Youtube theses properties : `privacyStatus = 'unlisted'` and `embeddable=true`.

When we call the Youtube API to only Update the privacy status of the video (to set it 'public'), we get the Embeddable option to be reset to false 

Is that a normal behavior ?

#### Environment details

  - OS: docker- ubuntu
  - PHP version: 7.4
  - Package name and version:
  google/apiclient => 2.9.1 
  google/apiclient-services => v0.168.0

#### Steps to reproduce

1. Create an object video instance of  \Google_Service_YouTube_Video()
2. set the Id
3. create an object status instance of \Google_Service_YouTube_VideoStatus()
4. set the PrivacyStatus to 'public' of the object $status
5. set the status property of the $video object with the object $status
6. send that to the video->update APi with 'id,status' part.

#### Code example

```php
        $video = new \Google_Service_YouTube_Video();
        $video->setId($videoId);
        $status = new \Google_Service_YouTube_VideoStatus();
        $status->setPrivacyStatus('public');
        $video->setStatus($status);

        $youtubeApi->videos->update('id,status', $video);
```

I precises that we already find a workaround by setting the Embeddable property of the $status object.
But in my opinion, this should not happen...

Thanks in advance,
XuruDragon

**Comment by saranshdhingra** [comment]
Hi @XuruDragon 
Apologies for the delay in response on this issue.

But I tried your code snippet and it worked perfectly for me.

The video I tried to update was private earlier and embedding wasn't allowed, after running the code snippet it became public, but the "Allow Embedding" option on youtube stayed unchecked. So, it's running as expected.

Perhaps you've already solved this, but regardless, if the issue persists please reopen this as I'll be closing it now :)
