### ISSUE TITLE
Internal error encountered when trying to fetch payments from an adsense child account.

### ISSUE THREAD

**Issue by XristMisyris** [googleapis/google-api-php-client-services#359]
#### Environment details

  - OS: Linux
  - PHP version:  7.4.1
  - Package name and version: google-api-php-client-services / v0.174.0

#### Code example

```php
$this->service = new \Google_Service_AdSense($this->client);
$payments = $this->service->accounts_payments->listAccountsPayments('accounts/pub-1111111111111')->getPayments();
```

When trying to retrive the list of payments from a child adsense account, we get the following error: 

```
{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
```

When we use the parent account it returns data successfully.

**Comment by bshaffer** [comment]
This seems to be an API error and not a client library error, so I am closing this as inactionable.
