### ISSUE TITLE
My Business API for reviews?

### ISSUE THREAD

**Issue by marcis** [googleapis/google-api-php-client-services#365]
Doesn't exist a Service class for My Business (w/o Account Manager) to get locations & reviews, please?

(as stated here: https://developers.google.com/my-business/reference/rest?hl=es-419)

**Comment by jdpedrie** [comment]
The API clients are managed by the API teams. Check out the [My Business Support Resources Page](https://developers.google.com/my-business/content/support) for ways to get in touch with the team. They may be able to publish that client for you to use. :)
