### ISSUE TITLE
Custom Search Api don't have constant for the scope like the other classes 

### ISSUE THREAD

**Issue by sadashivdalvi** [googleapis/google-api-php-client-services#382]
I am a developer of https://www.drupal.org/project/google_api_client and what I do is I read all classes which extend Google_Service and create a ReflectionClass object and read constants for scopes, I then show these scopes as a configuration to end user who can authenticate.

One developer reported to me that there are no scopes in Custom Search Api at https://www.drupal.org/project/google_api_client/issues/3219666

Can you add the constant so that /auth/cse shows up as a scope

**Comment by bshaffer** [comment]
These scopes are autogenerated from the [discovery doc](https://customsearch.googleapis.com/$discovery/rest?version=v1) (see [the documentation](https://developers.google.com/discovery/v1/reference/apis) for more), so we cannot add the scope unless it's added there. I can file an issue with the team to see if they'll add it, but I imagine this is working as designed.

**Comment by bshaffer** [comment]
@sadashivdalvi I spoke with the Custom Search API team. The reason they do not populate scopes is they **only** allow API Key authentication. Scopes are for OAuth2 authentication, which is not supported by their API.

**Comment by sadashivdalvi** [comment]
Thanks for the update @bshaffer
