### ISSUE TITLE
Safe browsing client refers to non existent v5 version

### ISSUE THREAD

**Issue by abadb** [googleapis/google-api-php-client-services#4238]
The Safebrowsing client refers to a v5 version. It was changed on this commit: https://github.com/googleapis/google-api-php-client-services/commit/9034d572d7780a468cd6092fd4196bb86ca3ad39

However, there are no API docs for this yet:

https://developers.google.com/apis-explorer/#p/safebrowsing/v5/

(They redirect to the v4 version)

Is this normal behaviour ?

**Comment by yash30201** [comment]
Hi @abadb, thanks for raising this issue.
This is definitely a strange behaviour. I'm checking this behaviour internally.

**Comment by yash30201** [comment]
Hi @dsazup , thank you for your patience. 

Yes I did check this issue and am working internally upon this and don't have any updates as of now. I'm expecting to update this issue with the status by end of this week. Sorry for the delay.

**Comment by yash30201** [comment]
There has been an override of the SafeBrowsing v4 client from  >= v0.319.0 of google-api-php-client-services. We are working on a fix, meanwhile please use [v0.318.0](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.318.0). We're really sorry for the trouble.

**Comment by yash30201** [comment]
This library is working as intended as we only publish the "preferred" version which is marked by the backend product team. 
I've raised an internal request with the product team to fix it as it's now an actionable from their side.

Meanwhile users are suggested to use [v0.318.0](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.318.0) of this library by mentioning this in `composer.json` of the `google/apiclient`.

_More on why we only publish preferred libraries as of now can be read [here](https://github.com/googleapis/google-api-php-client-services/issues/222#issuecomment-719752899)_
