### ISSUE TITLE
generator: Support a resources protocols parameter

### ISSUE THREAD

**Issue by metaodi** [googleapis/google-api-php-client-services#46]
The [Google Fusion Tables API](https://developers.google.com/fusiontables/docs/v2/reference/) describes the methods [importTable](https://developers.google.com/fusiontables/docs/v2/reference/table/importTable), [importRows](https://developers.google.com/fusiontables/docs/v2/reference/table/importRows) and [replaceRows](https://developers.google.com/fusiontables/docs/v2/reference/table/replaceRows)  with two different endpoints. One endpoint is to change metadata only, the other can be used to upload a file (e.g. a CSV) to import a table or update data in a table.

E.g. for `importTable`:

* Upload URI, for media upload requests: 
`POST https://www.googleapis.com/upload/fusiontables/v2/tables/import`
* Metadata URI, for metadata-only requests: 
`POST https://www.googleapis.com/fusiontables/v2/tables/import`

Currently this library only supports the "Metadata URI" and can therefore not be used to upload a CSV to Google Fusion Tables.

Please consider to add support for uploads for these methods, as this is their intended use. Without this, you force users to change data using SQL statements, which are bound to rate limits or write HTTP calls to the Fusion Tables API directly without using this library.

**Comment by mattwhisenhunt** [comment]
Blocked by #44

**Comment by dwsupplee** [comment]
@metaodi, sorry for the late response here. We should already have support for this, the key is to provide the `data`, `mimeType`, and `uploadType` options.

```php
$service = new Google_Service_Fusiontables($client);
$service->table->importRows(
    '{TABLE_ID}',
    [
        'data' => file_get_contents('/path/to/file.csv'),
        'mimeType' => 'application/octet-stream',
        'uploadType' => 'media'
    ]
);
```

Please feel free to re-open if there's anything else we can do to help!
