### ISSUE TITLE
Wrong return type in PHPDoc of UserinfoV2Me::get()

### ISSUE THREAD

**Issue by azerum** [googleapis/google-api-php-client-services#524]
PHPDoc of `UserinfoV2Me::get()` says that method returns `Userinfo`, but it should return `UserinfoModel`

```php
namespace Google\Service\Oauth2\Resource;

//Note the alias
use Google\Service\Oauth2\Userinfo as UserinfoModel;

/**
 * The "me" collection of methods.
 * Typical usage is:
 *  <code>
 *   $oauth2Service = new Google\Service\Oauth2(...);
 *   $me = $oauth2Service->me;
 *  </code>
 */
class UserinfoV2Me extends \Google\Service\Resource
{
  /**
   * (me.get)
   *
   * @param array $optParams Optional parameters.
   * @return Userinfo
   */
  public function get($optParams = [])
  {
    $params = [];
    $params = array_merge($params, $optParams);
    return $this->call('get', [$params], UserinfoModel::class);
  }
}
```

`get()` returns result of `$this->call()` ([defined here](https://github.com/googleapis/google-api-php-client/blob/master/src/Service/Resource.php#L86)). The third parameter of `call()` is `$expectedClass` - name of the class that should be returned. In this case it's `UserinfoModel::class`

I also tested the return type of `get()` with `var_dump()` to be sure, here is the output:
```
object(Google\Service\Oauth2\Userinfo)#52...
```

`UserinfoModel` is alias of `Google\Service\Oauth2\Userinfo`

**Comment by dwsupplee** [comment]
@azerum has this raised in issue your experience? My understanding is that the current output is correct, the alias we are using in this class shouldn't affect the return type.

**Comment by azerum** [comment]
Sorry if it want's clear from my post - actual return type of the function and return type written in PHPDoc are different.

The function returns `UserinfoModel`, which is alias for `Google\Service\Oauth2\Userinfo`.

PHPDoc says that function returns 'Userinfo'. PHP resolves type name 'Userinfo' relative to the namespace of the current file. Namespace of the current file is defined on this line:

`namespace Google\Service\Oauth2\Resource;` 

So the full name of the return type in PHPDoc is `Google\Service\Oauth2\Resource\Userinfo`

So again: function actually returns `Google\Service\Oauth2\Userinfo`, but PHPDoc says it's `Google\Service\Oauth2\Resource\Userinfo`

**Comment by azerum** [comment]
Why is this an issue?

IDE will assume that function returns type that is written in PHPDoc - `Google\Service\Oauth2\**Resource**\Userinfo` and will do typecheking with this type. But as this type is wron, typecheking will also be wrong.

This will lead to errors. For example, I thought that function returns `Userinfo` (as in PHPDoc). I have written function that accepts `Userinfo` object and stores it into the session. I have used type hinting to ensure that passed object is indeed `Userinfo`:

```
use Google\Service\Oauth2\Resource\Userinfo; //Note the type: as in PHPDoc, full type name with \Resource\ part

class Session 
{
    public static function setUserInfo(Userinfo $userInfo) 
    {
        $_SESSION['user_info'] = serialize($userInfo);
    }
}
```

Now I get `Userinfo` object and try to pass it to the function:

```
$oauth2 = new Google\Service\Oauth2($client);

$userInfo = $oauth2->userinfo_v2_me->get();
Session::setUserInfo($userInfo);
```

IDE doesn't show me any errors, because types match, but when I run this code, I get the following error:
<img width="1274" alt="изображение" src="https://user-images.githubusercontent.com/60925680/140058327-ddd43521-7b8a-482e-a066-d6547db05871.png">

> Argument #1 ($userInfo) must be of type Google\Service\Oauth2\Resource\Userinfo, Google\Service\Oauth2\Userinfo given

That is, `get()` acually returned `Google\Service\Oauth2\Userinfo` (`UserinfoModel` in it's code) and not the type I expected. Error happens because when using type hinting, PHP ensures that types are correct.

I can change the type hint to the type that `get()` actually returns like this:

```
use Google\Service\Oauth2\Userinfo; //Note the type again: now without \Resource\ subnamespace

class Session 
{
    public static function setUserInfo(Userinfo $userInfo) 
    {
        $_SESSION['user_info'] = serialize($userInfo);
    }
}
```

Code will work. But there is another problem: IDE still thinks that `get()` returns `\Resource\Userinfo`, because only thing it can see is PHPDoc, it can't inspect actual return type of method. So IDE thinks that I try to pass `\Resource\Userinfo` to my function `setUserInfo()`, that now expects different type - just `Userinfo`. IDE thinks that code has error:

<img width="743" alt="изображение" src="https://user-images.githubusercontent.com/60925680/140059307-940eebfa-f2be-42ce-9deb-b3908bb28743.png">

**Comment by azerum** [comment]
@dwsupplee First, it's confusing: as PHP is dynamically typed, the only way for me, as user of the API, to know what kind of object is returned from the function is to look at PhpDoc (or type annotation, which is absent here). But it turns out that return type is incorrect. Now to know propeties of the returned object I have to instpect it with var_dump()

Second, IDE is confused in the same way. If I store the result of the function in variable `$r = $userinfo->get()`, IDE will think that `$r` has the type TypeInPhpDoc, but actual type of `$r` is ActualReturnType. As TypeInPhpDoc != ActualReturnType, all type checks that IDE makes are wrong. 

If I try to pass `$r` to function that accepts TypeInPhpDoc parameter, IDE will think that code is correct. In runtime I will have an error, because type of `$r` doesn't match TypeInPhpDoc.

Hopefully this time I've explained this clear

**Comment by azerum** [comment]
@dwsupplee The problem is that PhpDoc and the alias refer to different types.

`Userinfo` in PhpDoc refers to the class `Userinfo` in the _current namespace_ of the file, that is, to the class in `Google\Service\Oauth2\Resource`. So the full class name is `Google\Service\Oauth2\Resource\Userinfo` (note `Resource` sub-namespace)

Actually returned object has class `UserinfoModel` - the alias of `Google\Service\Oauth2\Userinfo` (note no `Resource` here)

Both user of the API and IDE are confused about real return type. All IDE type checks are wrong, autocomplete is wrong, and so on

**Comment by bshaffer** [comment]
The issue can be found [here](https://github.com/googleapis/google-api-php-client-services/blob/main/src/Oauth2/Resource/UserinfoV2Me.php), and it does seem to indeed be a bug. We will need to fix this in the generator

**Comment by bshaffer** [comment]
It worked!!

https://github.com/yoshi-code-bot/google-api-php-client-services/blob/e17098cace46da51c24218cf78485cea03dd5ce4/src/Oauth2/Resource/UserinfoV2Me.php#L36
