### ISSUE TITLE
parameter 'include-historical-channel-data' missing in reports methods defintion

### ISSUE THREAD

**Issue by jokr-1** [googleapis/google-api-php-client-services#53]
The new parameter 'include-historical-channel-data' (added Feb 8, '17) in the YT Analytics API is not yet defined in the YouTubeAnalytics.php
Adding 
```
'include-historical-channel-data' => array(
                  'location' => 'query',
                  'type' => 'boolean',
                ),
```
to the reports methods array fixed the problem (https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/YouTubeAnalytics.php#L214). Else, the client returns no data when using the new parameter.

**Comment by mattwhisenhunt** [comment]
Blocked by #44
