### ISSUE TITLE
UrlNotifications->publish returns other type

### ISSUE THREAD

**Issue by ShkrabovLeonid** [googleapis/google-api-php-client-services#5419]
`php version 8.3.10`
`"google/apiclient": "^2.10"`
 
Here is part of my code:
 
```php
try {
  $client->setUseBatch( true );
  $service = new Indexing( $client );
  $batch = $service->createBatch();
  $updatedLinks = [];
  foreach ( ["https://example.com/link1", "https://example.com/link2"] as $link ) {
    /** @var Link $link */
    $request = new UrlNotification();
    $request->setUrl( $link );
    $request->setType( "URL_UPDATED" );
    $batch->add( $service->urlNotifications->publish( $request ) );
    $batch->execute();
  }
  return $updatedLinks;
} catch ( \Exception $e ) {
  throw $e;
}
```

<img width="1092" alt="Знімок екрана 2024-08-08 о 23 08 32" src="https://github.com/user-attachments/assets/d077dc73-fdac-434d-8c6a-2874a3ba948c">

The `$batch->add` method waits for the `RequestInterface` but `urlNotifications->publish` has PhpDoc comment `@return PublishUrlNotificationResponse`.
This seems to be incorrect. In reality, `urlNotifications->publish` returns a `GuzzleHttp\Psr7\Request`

Maybe I'm doing something wrong?
I found information about using batch with Indexing on
https://stackoverflow.com/questions/53481191/how-to-send-batch-request-with-google-indexing-api

**Comment by bshaffer** [comment]
Hello! Yes, you are correct that the PHPDoc is not fully correct. All methods return `GuzzleHttp\Psr7\Request` when `setUseBatch` is set to `true`. So the real PHPDoc values for all these _should_ be `@return PublishUrlNotificationResponse|Request`.
