### ISSUE TITLE
GA4 it is impossible sort by metric ascending

### ISSUE THREAD

**Issue by emimarz** [googleapis/google-api-php-client-services#548]
- OS: MacOS BigSur, Ubuntu
  - PHP version: 7.3
  - Package name and version: googleapis/php-analytics-data 0.7.0 and 0.7.1

#### Code example
In GA4 it is impossible sort metric asc, I also tried sending array and others methods but nothing works 

```php

            $order = new OrderBy();
            $mOrder = new OrderBy\MetricOrderBy();
            $mOrder->setMetricName('eventCount');
            $order->setMetric($mOrder);
            $order->setDesc(true);
            dump($order->serializeToJsonString());
            //   {"metric": {"metricName": "eventCount"}}

```

and that made an descending report

```php

            $order = new OrderBy();
            $mOrder = new OrderBy\MetricOrderBy();
            $mOrder->setMetricName('eventCount');
            $order->setMetric($mOrder);
            $order->setDesc(false);
            dump($order->serializeToJsonString());
            //   {"metric": {"metricName": "eventCount"}, "desc": true}
```

and that get an descending report

full example
```php
        $request = [
            'property' => 'properties/' . $property_id,
            'dateRanges' => [
                new DateRange([
                    'start_date' => '2020-01-01', 
                    'end_date' => '2020-12-31',
                ]),
            ],
            'dimensions' => [
                new Dimension([
                    'name' => 'eventName'
                ]),
                new Dimension([
                    'name' => 'searchTerm'
                ])

            ],
            'metrics' => [
            new Metric([
                'name' => 'eventCount',
            ]);
            ],
            'limit' => 100,
        ];
            $order = new OrderBy();
            $mOrder = new OrderBy\MetricOrderBy();
            $mOrder->setMetricName('eventCount');
            $order->setMetric($mOrder);
            $order->setDesc(false);
            $request['orderBys'] = [$order];

            $client->runReport($request);
```

I found that if I change in file
vendor/google/analytics-data/src/V1beta/OrderBy.php
private $desc = false;
to
private $desc = true;

start to work fine

**Comment by danoscarmike** [comment]
@bshaffer could you PTAL?

**Comment by bshaffer** [comment]
Hello @emimarz 

Firstly, the repo you're looking for is https://github.com/googleapis/google-cloud-php, which contains the code that gets split into the READ-ONLY https://github.com/googleapis/php-analytics-data as a separate composer package. You can file an issue [here](https://github.com/googleapis/google-cloud-php/issues/new) if you feel this is still an issue

Secondly, I am unable to reproduce this. Here is my code:

```php
require 'vendor/autoload.php';

use Google\Analytics\Data\V1beta\OrderBy;

$order = new OrderBy();

$mOrder = new OrderBy\MetricOrderBy();
$mOrder->setMetricName('eventCount');
$order->setMetric($mOrder);
$order->setDesc(true);
var_dump($order->serializeToJsonString());
// string(50) "{"metric":{"metricName":"eventCount"},"desc":true}"
$order->setDesc(false);
var_dump($order->serializeToJsonString());
// string(38) "{"metric":{"metricName":"eventCount"}}"
```

This is working as designed (as the default value is false), and does not match your examples above. Is it possible your examples are incorrect?

**Comment by danoscarmike** [comment]
Repo transfer was my fault - sorry about that!

**Comment by emimarz** [comment]
Hi @bshaffer I still having the issue
I don't create the issue in https://github.com/googleapis/php-analytics-data because is not enabled to do that
the issue is seen in the results in both cases result came in descending order because when you omit the field "desc" the API return descending but when I put  setDesc(false) is for ascending order

**Comment by emimarz** [comment]
can you check this pls because i receive descending data in both cases
$order->setDesc(true);
$order->setDesc(false);
