### ISSUE TITLE
PhotosLibrary missing since v0.200

### ISSUE THREAD

**Issue by philipsharp** [googleapis/google-api-php-client-services#557]
Service classes for `photoslibrary:v1` were added in 89309857710ed3d9789a57e0ae02e8ea70c4d249, and first included in the [v0.59 ](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.59) release.

Since the service regeneration including in the [v0.200](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.200.0) release, these classes are no longer included, although the API is still maintained and available.

**Comment by danoscarmike** [comment]
@bshaffer would you mind investigating? Possibly an issue with Discovery?

**Comment by danoscarmike** [comment]
This API is no longer listed in the discovery directory. Investigating with the product team.

**Comment by bshaffer** [comment]
Hi @philipsharp !
Unfortunately, this API was delisted from our list of supported APIs years ago. It wasn't removed from PHP until recently because when we released `v0.200.0`, we did a cleanse and removed all the now-unsupported libraries.

So this is working as designed, and if you would like to continue using that library, you'll need to use a pre-`v0.200.0` version of the services repo.

**Comment by philipsharp** [comment]
What's the criteria for a supported API?

**Comment by bshaffer** [comment]
It's up to the API teams themselves, we do not have control over it. They mark the APIs as "preferred" in their discovery configuration, and then those APIs get mirrored to [this repository](https://github.com/googleapis/discovery-artifact-manager/tree/master/discoveries), which is where this library generates them from.

It is possible (and not too difficult) to generate the PHP library yourself by downloading the discovery JSON and providing it to the generator in this repo.

```
# Clone this repo
git clone https://github.com/googleapis/google-api-php-client-services
cd google-api-php-client-services

# install the python dependencies
python2 -m pip install -e generator/ --user

# Download the photoslibrary JSON
curl 'https://photoslibrary.googleapis.com/$discovery/rest?version=v1' -o photoslibrary_v1.json

# Run the generator
python2 -m googleapis.codegen  --output_dir=output --input=photoslibrary_v1.json 
```

I've attached the result here for your convenience. Good luck and sorry for the confusion.

[photoslibrary_v1.zip](https://github.com/googleapis/google-api-php-client-services/files/7825004/photoslibrary_v1.zip)
