### ISSUE TITLE
Readonly is now a reserved keyword

### ISSUE THREAD

**Issue by bobvandevijver** [googleapis/google-api-php-client-services#577]
Readonly is now a [reserved keyword](https://www.php.net/manual/en/reserved.keywords.php) within PHP, so it can no longer be used within this library.

- https://github.com/googleapis/google-api-php-client-services/blob/main/src/Datastore/ReadOnly.php
- https://github.com/googleapis/google-api-php-client-services/blob/main/src/Firestore/ReadOnly.php
- https://github.com/googleapis/google-api-php-client-services/blob/main/src/Spanner/ReadOnly.php

#### Environment details

  - PHP version: 8.1
  - Package name and version: google/apiclient-services 0.229.0

**Comment by bshaffer** [comment]
I think the way forward here is to add `readonly` to the list of keywords. We could add an alias to the previous `ReadOnly` classes if this is too disruptive, but I think it should be okay.
