### ISSUE TITLE
MyBusiness API: Q&A endpoint unavailable

### ISSUE THREAD

**Issue by nekromoff** [googleapis/google-api-php-client-services#581]
`https://developers.google.com/my-business/reference/qanda/rest`

not available in the code.

**Comment by bshaffer** [comment]
Your API is right here: https://github.com/googleapis/google-api-php-client-services/tree/main/src/MyBusinessQA

```php
$mybusiness = new Google\Service\MyBusinessQA();
// call the API
```

**Comment by nekromoff** [comment]
Not it is, then it wasn't.
