### ISSUE TITLE
Missing report location and list recommend api in GMB v1 

### ISSUE THREAD

**Issue by arpansoni007** [googleapis/google-api-php-client-services#615]
Hi , 

I need info about two api's in gmb v1 .

1. Report Locations api 
 https://developers.google.com/my-business/reference/rest/v4/googleLocations/report

  Where is the new version of this in this library, if deprecating in future is there any alternate version of this for v1 version.

2. List Recommend Google Locations api
   in old version v4.9
   https://developers.google.com/my-business/reference/rest/v4/accounts/listRecommendGoogleLocations

  It is deprecating as mentioned in changelog , so is there any  upcoming or alternate version for  version v1 , if so please let me know with the reference link and availability in this library.

**Comment by bshaffer** [comment]
You can download the [4.9 version of this library for my business](https://developers.google.com/my-business/samples/previousVersions#v49) or pin to a previous version of this library before the update occurred using composer:

```
composer require google/apiclient-services:0.231.0
```
