### ISSUE TITLE
File naming problem - two files same name, different capitalisation

### ISSUE THREAD

**Issue by antalkiss** [googleapis/google-api-php-client-services#714]
Hi!

Unfortunately we stumbled upon the same problem as before in https://github.com/googleapis/google-api-php-client-services/issues/590 

There are two files with different capitalisation:

- `src/PlayIntegrity.php`
- `src/Playintegrity.php`

**Comment by erikn69** [comment]
Yes, it is happening again
@bshaffer did fix it on the last time 
```
Class Google\Service\Playintegrity located in
\vendor\google\apiclient-services\src\PlayIntegrity.php 
does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by bshaffer** [comment]
Thanks for the heads up, I'll take a look right now...

**Comment by bshaffer** [comment]
This looks like an improperly pushed file, so I just removed it: https://github.com/googleapis/google-api-php-client-services/pull/715

We added a GitHub action to make sure this didn't happen, but I forgot to make the check required, so GitHub was automerging even when it failed :(

I've fixed this so it doesn't happen again. Thanks for the the heads up.
