### ISSUE TITLE
MyBusinessAccountManagement is missing the List Locations function.

### ISSUE THREAD

**Issue by mnwalker** [googleapis/google-api-php-client-services#763]
#### Environment details

  - OS: Linuix
  - PHP version: 7.4
  - Package name and version: google/apiclient-services  v0.239.0

#### Steps to reproduce

  MyBusinessAccountManagement is missing the List Locations function.

 https://developers.google.com/my-business/reference/businessinformation/rest/v1/accounts.locations/list

API exists in link above, but SDK has no method or variable set.

MyBusinessAccountManagement class has locations, but only method is transfer, no list or get.

Locations is available in MyBusiness API but that is alreadyy deprecated.
https://developers.google.com/my-business/content/sunset-dates

**Comment by bshaffer** [comment]
You're looking at the wrong service. This API is in `MyBusinessBusinessInformation`. You can see the class [here](https://github.com/googleapis/google-api-php-client-services/blob/main/src/MyBusinessBusinessInformation/Resource/AccountsLocations.php#L87)
