### ISSUE TITLE
Exception thrown after gmb search location api response in vendor file in library.

### ISSUE THREAD

**Issue by arpansoni007** [googleapis/google-api-php-client-services#788]
#### Environment details

  - OS: Windows 10
  - PHP version: 7.4.3
  - Package name and version:
    "google/apiclient": "v2.8.3",
    "google/apiclient-services": "0.234.0",

#### Steps to reproduce
   I am using the both packages above in laravel 5.7 application and using search api for find location using location object
    [https://developers.google.com/my-business/reference/businessinformation/rest/v1/googleLocations/search]
  
  1. Prepare search request object and set a location object you need to find using setLocation method
  2. Call search api
  3.  You will get response but an exception will be thrown which will give result below:
  
   { 
     "error": {  
                    "code": 500, 
                   "message": "Internal error encountered.", 
                   "status": "INTERNAL"
                 } 
    }
   
    exception is thrown from below file in vendor on line no. 130
    vendor/google/apiclient/src/Http/REST.php
    
   
   Can anybody let me know why this exception throwing in for many locations ?

Thanks!
![Screenshot 2022-03-23 143434](https://user-images.githubusercontent.com/48259282/159664099-77525d47-7964-4085-8e4e-289be0ae6ed4.png)

**Comment by bshaffer** [comment]
This exception represents an API error. It means the API server is responding with a 500 error. This is a very rare error because it means something is wrong with the backend (e.g. the MyBusiness API itself). I imagine whatever was wrong with the backend, it's been resolved by now.
