### ISSUE TITLE
MyBusinessQA Service has wrong paths

### ISSUE THREAD

**Issue by unbreak** [googleapis/google-api-php-client-services#956]
In `src/MyBusinessQA.php` for `locations_questions` there are wrong paths for methods create and list, fot both should be:
```
'path' => 'v1/{+parent}/questions',
```
not:
```
'path' => 'v1/{+parent}',
```

#### Steps to reproduce

  1. try to call:
```
$qaService = new MyBusinessQA($client);
$questions = $qaService->locations_questions->listLocationsQuestions($locationName);
```
  2. You will get exception that read_mask is required field because its trying to get location not questions list for provided location.

**Comment by unbreak** [comment]
Fixing by #1010

**Comment by bshaffer** [comment]
These classes are autogenerated, so this change would be overwritten by the next release. Furthermore, if this is truly an error, it would be an error in the discovery API itself, and so the fix would need to go there.

The [discovery doc](https://mybusinessqanda.googleapis.com/$discovery/rest?version=v1) shows the path we have in the library here as the path for listing questions. There's nothing we can do here unless that changes. I would suggest [contacting the API team](https://support.google.com/business/contact/api_default) if you think this is an error. 

The maintainers of this repo only make sure the generated clients match the API's discovery doc, and do not support any specific API usage questions (there are over 200 APIs, so it would be impossible for us to do that)

**Comment by bshaffer** [comment]
I'm looking into the `flatPath` parameter in the discovery doc, as that seems to be closer to the URL you've provided

**Comment by bshaffer** [comment]
So, looking at the discovery doc, the parent parameter should contain "/questions" in the path:

```json
{
"list": {
    "parameters": {
        "parent": {
            "description": "Required. The name of the location to fetch questions for.",
            "location": "path",
            "required": true,
            "type": "string",
            "pattern": "^locations/[^/]+/questions$"
        },
    }
}
```

So the correct usage should be:

```php
$qaService = new MyBusinessQA($client);
$questions = $qaService->locations_questions->listLocationsQuestions('locations/LOCATION_NAME/questions');
```

I agree this is not very intuitive, but I believe this is how the API is designed.
